### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by Kramsch** [dev7355608/vision-5e#1]
Hello dev7355608,
i found this module while looking for an actual good vision module.
An older module (no longer supported for version 10) suggested vision-5e .
But I coulnd't find it in module list and no json Link or release link.

How can I install it?

Best regards,
Kramsch

**Comment by dev7355608** [comment]
I assume you're still on V10, right? This module is only compatible with V11.

**Comment by Kramsch** [comment]
Ah, sorry. Yes, I am still running with V10. 
Okay, thanks for the info! I will snapshot my machine and then update to look into it :D
