### ISSUE TITLE
Errors with Group Actors

### ISSUE THREAD

**Issue by LukasPrism** [dev7355608/vision-5e#10]
I seem to be getting a lot of errors with group actors in v11. First, just for having one in the sidebar:
<img width="416" alt="Screenshot 2023-06-21 at 4 28 50 PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/fcfa9ad4-f7d1-4624-b249-193a6b223051">

And then if I drag to the canvas:
<img width="412" alt="Screenshot 2023-06-21 at 4 29 42 PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/9fea37d0-2720-4a92-89bf-06df1f656d2c">
<img width="412" alt="Screenshot 2023-06-21 at 4 31 09 PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/280b1741-4a8f-4086-9e38-f243d0fadf05">

I feel like I can just ignore these but thought you should know. Doesn't seem to matter if I turn vision on or off. The group actor doesn't actually seem to be able to see at all.

Thanks for an awesome module btw, one of the biggest new features of v11! ;)

**Comment by dev7355608** [comment]
Thanks for the report! Forgot to skip non-character/NPC actors. Fixed in 1.3.2.

**Comment by LukasPrism** [comment]
Thanks for jumping on this so quickly. Sorry to say I'm seeing the exact same errors. All other modules disabled, world scripts disabled. I tried creating a new group actor with Starter Heroes and same issues. Maybe it's a dnd5e bug?

**Comment by dev7355608** [comment]
I missed half of the problem, because I didn't actually test a group token with vision enabled. Fixed it in 1.3.3.

**Comment by LukasPrism** [comment]
So speedy! Can confirm we're now error-free.

Thanks heaps.
