### ISSUE TITLE
What is the reason to disable basic vision?

### ISSUE THREAD

**Issue by moonbrew** [dev7355608/vision-5e#101]
https://github.com/dev7355608/vision-5e/blob/17151e533cfab7a2457cc6d4c9d75f08df92aacc/scripts/main.mjs#L138

My tokens now all have darkvision by default.

**Comment by dev7355608** [comment]
Basic Vision doesn't exist in dnd5e, and therefore it is removed.

**Comment by joaohanizelli** [comment]
I don't get it as well, every token with darvision makes no sense. Am I missing something here?
