### ISSUE TITLE
Token with regular vision unable to see in light

### ISSUE THREAD

**Issue by thystra** [dev7355608/vision-5e#109]
I am testing a 2024 character that I brought in via DDBimporter to Foundry. When the character is in light, he can't see monsters. The character has no special vision enhancements. 
![Screenshot from 2024-09-27 16-40-20](https://github.com/user-attachments/assets/2d009d16-9995-4498-8329-57dd03af41eb)

When I disable Vision5e module, he can see the monsters etc. in light. 

![Screenshot from 2024-09-27 16-44-32](https://github.com/user-attachments/assets/750a53ea-5054-4f53-ad2a-0740743f0a05)

Foundry V12 331
Vision5e 2.5.1
DND5e 4.0.3
Character sheet: https://www.dndbeyond.com/characters/132976955

Characters should be able to see in normal light if they have no special abilities.

**Comment by dev7355608** [comment]
Could you show me the Detection Modes tab in the Token Config for this token?

Have you tested for module incompatibles? Does this problem occur with Vision 5e being the only active module?

**Comment by thystra** [comment]
![image](https://github.com/user-attachments/assets/159ff8b8-1466-4955-84b0-02df003efe57)

It works normally when Vision5e and Find the Culprit are enabled. 

With Alternate Token Visibility disabled, the issue goes away.

**Comment by dev7355608** [comment]
Alternative Token Visibility is not compatible with Vision 5e (see https://github.com/caewok/fvtt-token-visibility/issues/84 and https://github.com/caewok/fvtt-token-visibility/issues/87).
