### ISSUE TITLE
Vision Angle / "Hearing" dead creatures

### ISSUE THREAD

**Issue by Cilona** [dev7355608/vision-5e#11]
When you play with a vision angle that is not 360° and a token looks away from a as dead marked creature they can still "hear" them.
![image](https://github.com/dev7355608/vision-5e/assets/70647117/bf38e67f-610d-45ff-870b-7fd620a8ffee)
![image](https://github.com/dev7355608/vision-5e/assets/70647117/0f42b06f-4d03-45f2-b0d8-be52fe4da1de)

**Comment by dev7355608** [comment]
I assume what you asking is unrelated to the vision angle: you just asking for hearing to not detect dead tokens, correct?

**Comment by Cilona** [comment]
Well if i think about it, yes it is unrelatetd to the vision angle, and yes not hearing dead tokens would be a option?

**Comment by R0TEAM** [comment]
to be correct - not hearing anything in D&D5 would be nice ... it is not an rule ... and is a very situative option if an creature is dedected by hearing (and then nearly all times only if he moves and not if he standing still .....) - so i dont need "hearing" at all in D&D5 ....

**Comment by LukasPrism** [comment]
Maybe have a read of this article. It’s a pretty good summary of how invisibility actually works: https://www.belloflostsouls.net/2022/01/dd-invisibility-doesnt-work-the-way-you-think-it-does.html

**Comment by R0TEAM** [comment]
I dont need an article how the autor think invisibility should work - sorry - but in the official 5e rules nothing is say from "hearing" ....
And even if the hearing would be implemented carefull - where is not working anyway as it is modifyed from so many things the engine could never understand > is the char moving, how fast, how is his closing modify this, how is the underground, how is the overall surounding noise level ... and so one ... < - i simply dont need an dedection mode i cant control as DM - then this mod is an dead end for me.

**Comment by Cilona** [comment]
If you don't want any hearing at all, you can just go and disable the hearing of the tokens in their detection, just set the hearing radius to 0ft and you don't have hearing anymore.

But in general this is not about invisibility or hearing in general. It's about "hearing" a creature which is dead on the floor not doing anything, not able to do anything, and showing up on the screen cluttering the view.

The makeshift solution that we came up in last nights session was to just whenever a creature is dead, the DM also gave the creature the status effect of "Inaudible" that solved the problem somewhat.

We tried to get a macro working to be able to set the creature dead and Inaudible at the same time, but we didn't got it to work properly.

A easy solution to this issue would be a macro. If someone could help me with that, would be highly appreciated.

**Comment by LukasPrism** [comment]
Do you use Dfred’s CE? You could customise the Dead status effect to also apply Inaudible statusEffect. Just tested and it works great.

**Comment by R0TEAM** [comment]
It looks i get many solutions (i dont like to say useles - but this i feel...) - but the ground problem dont get away ...
I DONT need or WANT any hearing option in my D&D5 game - simply .... 
I dont want to get this, and then i musst disable it on all chars or use macros .... how stupid is this, first to install an mod and then manual disable on many tokens the unwanted part - better not install the mod > simply solution ...
I have used Perfect Vision long time - a good mod, but if i get things i dont like (and it is not global possible to disable it simply in the mod settings) - then i am done with this mod - have fun, but not for me

**Comment by dev7355608** [comment]
- Added a setting to configure the default range of vision.
- Hearing and Tremorsense are no longer able to detect dead (defeated) tokens.

https://github.com/dev7355608/vision-5e/releases/tag/v1.4.0
