### ISSUE TITLE
An actor/token with Blindsight when the scene goes dark (night time)

### ISSUE THREAD

**Issue by YenBenGrey** [dev7355608/vision-5e#117]
Hello, 

I could well be doing something wrong but a character in my game has blindsight 10 feet, however when the sun goes down on a scene, the 10 foot radius goes dark too. With Blindsight the scene going darker shouldn't make any difference, right? 

In Magical Darkness it dims a little but due to it dimming a little when the scene is dark and they are in Magical Darkness, they cannot see much. :-(

V12.331
DND5e v 4.0.4
Vision 5e v 2.5.3

**Comment by dev7355608** [comment]
Looks like I might have accidentally changed the brightness of the Blindsight vision mode to -1 when it should be 1. I'll investigate further in the coming days if I don't forget.

**Comment by dev7355608** [comment]
https://github.com/dev7355608/vision-5e/releases/tag/v2.5.4
