### ISSUE TITLE
Adding Vision via Magic Item

### ISSUE THREAD

**Issue by ProfessorPeregrine** [dev7355608/vision-5e#123]
Goggles of Night grant darkvision 60' if you don't have it or extend your darkvision to 120' if you do. Is it possible to detect this with vision 5e?

**Comment by dev7355608** [comment]
Add an active effect to this item:

`system.attributes.senses.darkvision` | Add | 60

I think the goggles in the 5e magic items compendium should already be set up like this.

**Comment by ProfessorPeregrine** [comment]
That worked! The item in the SRD does not have that active effect.
