### ISSUE TITLE
Blind and Deaf not disabling senses properly

### ISSUE THREAD

**Issue by DishonoredRaven** [dev7355608/vision-5e#13]
Creatures are still detected with darkvision while blinded, and still detected through hearing while deaf. Also not sure if a bug or not, but blinded should apply to all sight-based detection modes, such as devil's sight, ghostly gaze, light perception, truesight, etc.

https://github.com/dev7355608/vision-5e/assets/33526316/fa65631f-78ed-4c4d-8f5b-a7761f5911c9

**Comment by dev7355608** [comment]
Working for me in 1.5.0. It doesn't look like you have the latest version: I don't see the Burrow status effect. Check your installed version.

**Comment by DishonoredRaven** [comment]
You were correct, I was on an outdated version, but I'm still getting the same problem with 1.5.0. Module list included, just in case.


https://github.com/dev7355608/vision-5e/assets/33526316/f5cc32c2-ab8b-4eb0-9633-c7f9a2352714

**Comment by DishonoredRaven** [comment]
Did further testing, seems to be an issue updating the screen after applying the effects.

https://github.com/dev7355608/vision-5e/assets/33526316/096ccc8d-4173-4bee-969f-ef3c66fdae92

**Comment by dev7355608** [comment]
Could you test it without other modules enabled. If that works, try reenabling until it fails. Or use the *Find the Culprit* module.

**Comment by DishonoredRaven** [comment]
Found it, looks like there's an updating or rendering issue in one of the other modules, it's doing it to more than just yours. Sorry for the false alarm!
