### ISSUE TITLE
[Request] Add Paladin's Divine Sense

### ISSUE THREAD

**Issue by dineshm72** [dev7355608/vision-5e#15]
https://www.dndbeyond.com/classes/paladin#ClassFeatures 

The presence of strong evil registers on your senses like a noxious odor, and powerful good rings like heavenly music in your ears. As an action, you can open your awareness to detect such forces. Until the end of your next turn, you know the location of any celestial, fiend, or undead within 60 feet of you that is not behind total cover. You know the type (celestial, fiend, or undead) of any being whose presence you sense, but not its identity (the vampire Count Strahd von Zarovich, for instance). Within the same radius, you also detect the presence of any place or object that has been consecrated or desecrated, as with the [hallow](https://www.dndbeyond.com/spells/hallow) spell.

**Comment by LukasPrism** [comment]
I was considering asking if exposing an API would be worthwhile so we can specify types for the module to detect, but the only other non-homebrew use case I can think of is Primeval Awareness.

**Comment by dev7355608** [comment]
Added *Divine Sense* in 1.6.0. https://github.com/dev7355608/vision-5e/releases/tag/v1.6.0
