### ISSUE TITLE
Option to disable  added status effects

### ISSUE THREAD

**Issue by roleoutgames** [dev7355608/vision-5e#16]
Can we add an option to not add the burrowing and other status effects?  It clutters the status effect menu with options I do not intend to use.

**Comment by dev7355608** [comment]
I assume that there are core status effect you don't need and have removed. What module do you use for that, or do you have a world script?

**Comment by roleoutgames** [comment]
I use Convenient effects and their option to replace the core status effects. It's an option in their module settings. However, it doesn't catch the additional effects added by your module. 
![Screenshot 2023-07-02 174547](https://github.com/dev7355608/vision-5e/assets/115042355/0fb4bf37-7424-4789-a512-a045fdea518b)

**Comment by dev7355608** [comment]
I plan to add Vision 5e's status effects as CE effects, which will allow you to add/remove them from the status effect HUD just like any other CE effect.

**Comment by roleoutgames** [comment]
Fantastic, that sounds like the right solution. Thank you for looking into it!

**Comment by dev7355608** [comment]
https://github.com/dev7355608/vision-5e/releases/tag/v1.7.0
