### ISSUE TITLE
[Compatibility Issue] Levels Module and Vision/Detection v1.6.0

### ISSUE THREAD

**Issue by onekinddonut** [dev7355608/vision-5e#19]
Describe the Bug:
There seems to be a compatibility issue with the Levels module and the latest version of the Vision/Detection module. 
Tokens on canvas are no longer visible above the map tiles in the levels module. When clicking on the tokens, it shows the token on a background layer with no map below them.

I rolled back to 1.5.0 and it works just fine.

I assume it is because the map tiles in the levels module are recommended to be Overhead or in the Foreground, so the map tiles are going over the tokens? I could change them to not be Overhead and it will show the token, but the levels module will not work as intended. 

Screenshots:
What it shows in 1.6.0

![1](https://github.com/dev7355608/vision-5e/assets/135482651/fffd2404-f275-496b-b273-ac25605b6adc)
![2](https://github.com/dev7355608/vision-5e/assets/135482651/11f877cd-6a53-47fd-9f42-1f400c31a7fb)

What it shows in 1.5.0
![3](https://github.com/dev7355608/vision-5e/assets/135482651/1f0ecbce-8bf6-4141-b53e-f650f6f096ca)

Version Info:
Foundry Version 11.302
System DnD 5e
Module version 1.6.0

Modules used:
Vision/Detection 5e
Levels
Libwrapper
TheRipper93's module hub
wall height

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 1.6.1.
