### ISSUE TITLE
Detect Evil and Good and Divine Sense

### ISSUE THREAD

**Issue by Arthurneto1307** [dev7355608/vision-5e#21]
In the character sheet of the 5th edition there is no option to put Creature type, so the detections for Divine Sense and Detect Evil and Good do not work with character actors, only npc actors.
Is there a possibility for you to add a detection method in addition to the usable creature type for character actors? Maybe look at Race box on Character sheet? i know we can detect poison with a poison weapon, so i would like to have that possibility. I love your module. It's very creative.

On the other hand, I would like a more customizable way to have Hearing of different range instead of fixed for everyone.

**Comment by dev7355608** [comment]
I think dnd5e 2.3.0 solve this issue with the Race Advancement changes. I imagine creature type will be included considering there are a number of 5e races that are not humanoid. But I'd have to double checked.

> On the other hand, I would like a more customizable way to have Hearing of different range instead of fixed for everyone.

You can customize the hearing range of any token by simply adding the Hearing detection mode with your range of choice. It will override the default range.

**Comment by Arthurneto1307** [comment]
Where did you see this version 2.3.0? How long will it take for this version to be released? Anyway, it would be very useful to add an actor.type option of character and in the actor.system.details.type.value an option for system.details.race.

In this part of Divine Sense and Detect Evil and Good
    _canDetect(visionSource, target) {
        if (!(target instanceof Token)) return false;
        if (target.document.hasStatusEffect(CONFIG.specialStatusEffects.BURROW)) return true;
        const actor = target.actor;
        if (!(actor && actor.type === "npc")) return false;          <----- here character too
        const type = actor.system.details.type.value;                  <----- here system.details.race too
        return type === "celestial"
            || type === "fiend"
            || type === "undead";
    }

**Comment by dev7355608** [comment]
You sparked a small discussion among dnd5e devs about this PC creature types yesterday: PC creature types are definitely coming with dnd5e 2.3.0. I don't have a release date for you (there isn't one yet). Not so soon I think.

I could try to infer the creature type from the race. But only of official 5e races. Not sure if that will help you.
- Autognome => Construct
- Centaur => Fey
- Changeling => Fey
- Fairy => Fey
- Hexblood => Fey
- Plasmoid => Ooze
- Satyr => Fey
- Thri-kreen => Monstrosity
- everything else => Humanoid

**Comment by LukasPrism** [comment]
This would be great, and nice to have it comprehensive like this – although only the fey ones would be necessary as things stand.

**Comment by dev7355608** [comment]
Centaur, Changeling, Fairy, Hexblood, and Satyr are now detected by Detect Evil and Good.

https://github.com/dev7355608/vision-5e/releases/tag/v1.6.3
