### ISSUE TITLE
[Feature Request] Optional imprecise indicator customisation

### ISSUE THREAD

**Issue by LukasPrism** [dev7355608/vision-5e#23]
Hey there, congrats on publishing Limits and also having your SRD updates merged into 2.3.0!

This is a request I made earlier but formalising it here.

As a bit of background, our table has been playing official FVTT adventures (currently A House Divided) and we're really appreciating the atmosphere and level of detail. The canvas art has inspired me to make some changes to the way we play:
- We've made top-down player tokens so they better fit with the art style and NPCs.
- With Aedif's help we now have settings in Token Variant Art to hide all AEs on tokens, revealing them only on hover/alt hold.
- Aedif has created a module at my suggestion (Tactical Grid), which hides the grid except on hover/alt. We do like having a grid but not at the expense of the art.

With that out of the way, my request is to allow some user customisation of how the imprecise indicator appears for unseen tokens (the mystery man / cowl).

Here's how it appears in a dark corridor in AHD:
<img width="900" alt="Screenshot 2023-07-03 at 2 39 25 PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/d50c058f-9cf8-4bd7-948f-13e40868def1">

And here's how they look when I got Engulfed by a shambling mound (yes those large cowled men are shambling mounds):
<img width="1213" alt="Screenshot 2023-07-09 at 8 45 23 PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/9df092b6-2451-4a2f-b0c1-f1670af6af3e">

I know it is subjective but we feel the icons are too impactful and kill some of the atmosphere.

We would be happy if the indicator was simply the sonic animation you have inside the icon – even if it's harder to see that's not really an issue, the player will just need to be paying attention (as they should). I did try to find the cowl icon in your code to see if I could have a play myself as a test but didn't manage that :/ Maybe it's a core thing.

~~The only difficulty could be the different colors for different detection modes. I'm sorry I don't really know the answer to that, I know in Sequencer it's possible to recolor animations very nicely using the ColorMatrix filter. Perhaps you have some other ideas? If not, even just an option to adjust only the 'hearing' mode indicators would be hugely appreciated.~~ Duh, the other detection modes already have colored anims!

Many thanks again for your outstanding modules. I can't wait to start playing my warlock again, with the darkness/devils sight combo.

Cheers

**Comment by gambit07** [comment]
+1 to the above, would love a more subtle option!

**Comment by M0nk3yy** [comment]
Yeah, I agree that just having the sound waves as a circular emitter would be nice.

**Comment by LukasPrism** [comment]
FWIW I've managed to demonstrate exactly what I'm after with a single line of extra code (by complete dumb luck):
<img width="579" alt="Screenshot_2023-07-21_at_6 47 10_PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/9723ccc0-35fd-4e15-bb85-9e2a60de0f38">

Here's how out of sight tokens look:
<img width="669" alt="Screenshot 2023-07-21 at 6 44 13 PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/d9658793-ecf2-4695-8eb5-9d4ef33ee9e6">

And invisible ones:
<img width="866" alt="Screenshot_2023-07-21_at_6 45 37_PM" src="https://github.com/dev7355608/vision-5e/assets/104886594/24ee01b0-22e2-4e3a-b9b8-2d35b1afc02e">

No idea if this is a terrible idea performance-wise or anything, was just looking at the API docs and trying stuff :)

**Comment by M0nk3yy** [comment]
Oh, looks good! I'll definitely give that a try.

**Comment by LukasPrism** [comment]
> Oh, looks good! I'll definitely give that a try.

If you want the anim to be more prominent, beef up the outline color to 1.5ish for each value

**Comment by dev7355608** [comment]
Replaced the hearing detection filter: no mystery man anymore, only the wave effect.

https://github.com/dev7355608/vision-5e/releases/tag/v1.7.0
