### ISSUE TITLE
Choose rarity for Detect Magic

### ISSUE THREAD

**Issue by discodotgg** [dev7355608/vision-5e#24]
Hello,

Would it be possible to add an option to choose the base rarity for detect magic items? Currently set as COMMON, but as you pointed out, there is an ocean of items that are configured wrong in the compendium packs.

Thanks

**Comment by dev7355608** [comment]
dnd5e 2.3.0 is going to fix the rarities of compendium items and will make `magical` a property of items, which means that Detect Magic will no longer have to rely on the rarity to identify magical items.

**Comment by dev7355608** [comment]
I lied: the `magical` property won't make it into dnd5e 2.3.0.

**Comment by dev7355608** [comment]
Common items are no longer considered magical until we get the `magical` field.

https://github.com/dev7355608/vision-5e/releases/tag/v1.7.0
