### ISSUE TITLE
The module is not correctly implementing Devil's Sight's interaction with Dim Light

### ISSUE THREAD

**Issue by LawfulGreen** [dev7355608/vision-5e#25]
Hi,

According to this explanation from JC https://twitter.com/JeremyECrawford/status/957031642979221504?s=20, Dim Light and Devil's Sight should not interact. So, if a creature has DS but not Darkvision (or what they're looking at is at a distance where Darkvision wouldn't apply), they would still see Dim Light as Dim Light, and only full darkness will be treated as bright light for them.

This is not what we see with this module:

In the image below, the lamp is 5ft bright, 25ft dim light. When the character with Devil's Sight (no darkvision) is not selected, we can clearly see both the dim and bright portions, as well as the darkness beyond.

![Not Selected](https://github.com/dev7355608/vision-5e/assets/136001967/85e98f99-c9b5-4b77-98d6-1b658acecee5)

But when selected, the distinction disappears, and the dim light is treated as bright light, even though the character doesn't have darkvision.

![Selected](https://github.com/dev7355608/vision-5e/assets/136001967/0a7417ca-1200-4c09-ac44-8ed39997895c)

**Comment by FurtherV** [comment]
How did you actually manage to make Devil's Sight red? For me its like a light gray overlay but Devil's Sight should not have an overlay at all, it should act like normal vision in total darkness, correct?

**Comment by LawfulGreen** [comment]
The red is from a colored light source, and is just there to illustrate the effect

**Comment by dev7355608** [comment]
The vision effect and brightness are always applied to areas that are illuminated by a light source; there's not option to exclude illuminated areas in core. It would require a lot of work and patching to make this work in this module. There's also the issue that darkvision boosts dim to bright outside of range. Both are limitations we have to accept for now until core addresses them.
