### ISSUE TITLE
Not an issue, a request for Magic Awareness feature

### ISSUE THREAD

**Issue by YenBenGrey** [dev7355608/vision-5e#29]
Very similar to Detect Magic apart from it lasts 1 turn and the radius is 60 feet.

**Comment by YenBenGrey** [comment]
This is solved, I have used ATL. Not sure if you close these things, not sure on the protocol :-)

**Comment by dev7355608** [comment]
Thanks for letting me know about this ability. I'll add it to the list of automated active effects so that ATL isn't required to get this working.

**Comment by dev7355608** [comment]
Done.

https://github.com/dev7355608/vision-5e/releases/tag/v1.8.0
