### ISSUE TITLE
[Documentation] Vision Limitation mod hyperlink

### ISSUE THREAD

**Issue by M0nk3yy** [dev7355608/vision-5e#3]
Hi dev,

The readme references the module `Vision Limitation` but its hyperlink leads back to this module. Just wanted to flag this in case it is an error, but I understand this might just be a module that is still WIP and unpublished etc.

Thanks.

**Comment by dev7355608** [comment]
The module is going to be released soon. Hopefully this weekend. It's Perfect Vision's Vision Limitation feature as its own module.

**Comment by dev7355608** [comment]
https://github.com/dev7355608/limits
