### ISSUE TITLE
Video to show why it would be nice to have normal sight as option

### ISSUE THREAD

**Issue by R0TEAM** [dev7355608/vision-5e#31]
I have thinked numerous times why darkvision is different to Normal Sight (D&D5) ....
have seen a difference - but cant nail it down ....
Then i have an scene where i finaly found the answer ...
(have maked an Video...)
https://youtu.be/9EjjqZpkb7s
as you can see ... (i explain)
In the GM sight (and for all player that use not darkvision and use normal sight, the difference between bright light, and dimm light zones is clear visible ...
If i select the player, you cant see the difference between bright/dimlight anymore (or only hard)
This is the reason i would like to see an additional switch to normal sight in the nice drop down list where the player can select the sight variant.
That he can see the scene in the same way as player/NPCs/Monsters that have normal sight.

**Comment by dev7355608** [comment]
Removed the dim-to-bright boost of Darkvision, which means Darkvision players can enjoy the lighting just like non-Darkvision players.

https://github.com/dev7355608/vision-5e/releases/tag/v1.9.0
