### ISSUE TITLE
DFreds CE v5.1.0 changes break compatibility.

### ISSUE THREAD

**Issue by thatlonelybugbear** [dev7355608/vision-5e#32]
I think the latest update of DFreds CE changed when the actual effectDefinitions are setup so Vision 5e cannot add the ones needed as things now stand.

What one could do is just 
```js
const customStatusEffects = [
    {
        statuses: ["burrow"],
        //id: "burrow",
        name: "Burrowing",
        icon: "modules/vision-5e/icons/burrow.svg"
    },
    {
        statuses: ["disease"],
        //id: "disease",
        name: "Diseased",
        icon: "icons/svg/biohazard.svg"
    },
    {
        statuses: ["ethereal"],
        //id: "ethereal",
        name: "Ethereal",
        icon: "modules/vision-5e/icons/ethereal.svg"
    },
    {
        statuses: ["fly"],
        //id: "fly",
        name: "Flying",
        icon: "icons/svg/wing.svg"
    },
    {
        statuses: ["inaudible"],
        //id: "inaudible",
        name: "Inaudible",
        icon: "modules/vision-5e/icons/inaudible.svg"
    }
];

await game.dfreds.effectInterface.createNewCustomEffectsWith({activeEffects:customStatusEffects});

for (const {name} of customStatusEffects)
    await game.dfreds.effectInterface.addStatusEffect(name);
ui.notifications.warn("Foundry must be reloaded to update token status effects.", { permanent: true });
```
after loading the world and reload once to get rid of any Hook timing issues 🤷

**Comment by txm3278** [comment]
For more information on what changed, this was the [PR](https://github.com/DFreds/dfreds-convenient-effects/pull/266#issuecomment-1615832657). Effects are now initializes in setup instead of ready.

**Comment by kaelad02** [comment]
In the `compatibility.mjs` file, it has a hook that runs on `setup` that changes how `EffectDefinitions#initialize` works to add three more effects. Now that CE is initializing `EffectDefinitions` earlier, in the `setup` phase, that code doesn't kick in anymore. The first thing I'd try is seeing if this can be changed to an `init` hook. The `game.dfreds.effects` variable is instantiated very early on, technically even before `init` so I'd guess that'd do the trick.

And just to be absolutely clear, here's the hook I think can be switched from `setup` to `init`: https://github.com/dev7355608/vision-5e/blob/9ad5c3a1b877391de5fe00e6beb77363663620aa/scripts/compatibility.mjs#L99C28-L99C28

**Comment by dev7355608** [comment]
Thanks. Fixed it.

https://github.com/dev7355608/vision-5e/releases/tag/v1.8.1
