### ISSUE TITLE
Conflict with Monks Active Tile 'Create Actor' function.

### ISSUE THREAD

**Issue by Tatonker** [dev7355608/vision-5e#33]
I had a working Monks Active Tile Trigger tile that when clicked would hide itself and create a Mimic token in its place using an actor from the side bar (a mimic chest). As soon as I enable V5E the tile triggers up to the point of creating the token then throws a UI error and the following console error:
```js
foundry.js:753  Error: TokenDocument5e validation errors:
  detectionModes: 
    0: 
      range: must be a finite number
    at DataModelValidationFailure.asError (commons.js:3805:14)
    at TokenDocument5e.validate (commons.js:7070:61)
    at new DataModel (commons.js:6824:12)
    at new Document (commons.js:7489:3)
    at new BaseToken (commons.js:12168:3)
    at new ClientDocumentMixin (foundry.js:13894:7)
    at new CanvasDocument (foundry.js:13228:10)
    at new TokenDocument (foundry.js:24710:1)
    at new TokenDocument5e (token.mjs:6:16)
    at new TokenDocument5e (automation.mjs:138:34)
    at #preCreateDocumentArray (foundry.js:13450:15)
    at ClientDatabaseBackend._createDocuments (foundry.js:13343:73)
    at ClientDatabaseBackend.create (commons.js:8535:19)
    at async TokenDocument5e.createDocuments (commons.js:7864:23)
    at async Promise.all (index 0)
    at async TileDocument.fn (actions.js:1293:38)
    at async TileDocument.runActions (monks-active-tiles.js:4034:56)
```
I've noticed that the Mimic in question (DDB import version) has a Detection Mode - Light Perce/ption = Infinity which could be the problem. With V5E disabled it works properly, as soon as V5E is enabled it throws that error. Dragging the actor from the sidebar works, so it is something going on with the token creation from MATT and how it somehow relates to V5E.

There was a suggestion on the Foundry Module Troubleshooting channel to change the range to a finite number like 100, but the option is greyed out and I see no other way to change it.
![image](https://github.com/dev7355608/vision-5e/assets/70360365/51d34b89-1a17-46ea-9dde-732c85c08a06)
![image](https://github.com/dev7355608/vision-5e/assets/70360365/64a3f280-60a0-4106-a07b-b7d62bdb824d)

**Comment by Tatonker** [comment]
I've also raised a question on the MATT discord to see if they can alter the way their Create Actor option works and will accept an 'Infinity' Light Perception input.

**Comment by dev7355608** [comment]
I suspect MATT creates the token from the prepared data instead of the source data (`.toObject(false)` instead of `.toObject(true)`).

You can override any of the automatically prepared detection modes by adding another detection mode entry with the same name and your preferred range.

**Comment by Tatonker** [comment]
Thanks, we tried that and it worked, but adding a defined range to every token in a compendium / world is time-consuming. I've added a ticket on his github with the information above and a link to a short conversation we had on the MATT discord channel. Hopefully this is something he can update on his end.

Thanks for your attention, but this can probably be closed as it looks to be a MATT issue.

**Comment by dev7355608** [comment]
I changed the range to 1e15 instead of Infinity, which means no more validation errors. But if MATT creates the token from the prepared data, it means that the automatically configured detection modes based on the actor senses, active effects, etc. are snapshotted at this moment in time, which means that changes to the actor senses or active effects won't have an effect of the created token's detection modes anymore.
