### ISSUE TITLE
Unexpected error when loading world with Vision 5e and DFreds Convenient Effects

### ISSUE THREAD

**Issue by T-Whiz** [dev7355608/vision-5e#34]
The following error message is displayed when a world is loaded with Vision 5e and DFreds Convenient Effects enabled:
```
Uncaught (in promise) Error: You may not set a World-level Setting before the Game is ready.
    at #setWorld (foundry.js:3329:30)
    at ClientSettings.set (foundry.js:3314:58)
    at Settings.addStatusEffect (settings.js:524:26)
    at EffectInterface.addStatusEffect (effect-interface.js:303:26)
    at Object.fn (compatibility.mjs:181:51)
```

Foundry Virtual Tabletop: Version 11 Stable, 11.307
Game System: dnd5e, 2.2.2
Active modules:
Vision 5e 1.9.0
DFreds Convenient Effects 5.1.0
libWrapper 1.12.13.0
socketlib 1.0.13
The Forge 1.10

**Steps to recreate**:
1. Disable all modules aside from Vision 5e, DFreds Convenient Effects, and dependencies, then reload the world.

Attached screen shot and log for reference.
![image](https://github.com/dev7355608/vision-5e/assets/101904996/7e7e9aaa-17fc-4bcc-9ea4-995b4b043eac)
[log.log](https://github.com/dev7355608/vision-5e/files/12294819/log.log)
[support details.txt](https://github.com/dev7355608/vision-5e/files/12294822/support.details.txt)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed.

https://github.com/dev7355608/vision-5e/releases/tag/v1.9.1
