### ISSUE TITLE
TypeError: Error thrown in hooked function '' for hook 'renderSettingsConfig'. Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by thatlonelybugbear** [dev7355608/vision-5e#35]
With Vision 5e enabled, with lots of other modules active too, when I open the Configure settings menu this error is being logged on Foundry 11.307 and dnd5e 2.3.0, Vision 5e v1.9.1
```js
foundry.js:753  TypeError: Error thrown in hooked function '' for hook 'renderSettingsConfig'. Cannot read properties of null (reading 'value')
    at Object.fn (settings.mjs:32:5)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ExtendedSettingsConfig._render (foundry.js:5777:13)
    at async ExtendedSettingsConfig._render (foundry.js:6452:5)
    at async ExtendedSettingsConfig._render (foundry.js:70443:5)
```
I just added a small check for `if(!defaultHearingRange) return;` in `settings.mjs:31`, but not sure if that is OK in the long run.
```js
Hooks.on("renderSettingsConfig", (app, html) => {
    const defaultHearingRange = html[0].querySelector(`input[name="vision-5e.defaultHearingRange"]`);
    
    defaultHearingRange.value ||= 0;
    defaultHearingRange.min = 0;
    defaultHearingRange.step = 0.01;
    defaultHearingRange.required = true;

    html[0].querySelector(`[data-setting-id="vision-5e.defaultHearingRange"]`).classList.add("slim");
    html[0].querySelector(`[data-setting-id="vision-5e.defaultHearingRange"] label`)
        .insertAdjacentHTML("beforeend", ` <span class="units">(ft)</span>`);
});
```

**Comment by dev7355608** [comment]
I can't reproduce it. That's really odd. Are there any other error message before this one? I feel like there should be.

**Comment by thatlonelybugbear** [comment]
OK I will have to test it some more then to find specific repro steps 👍 

It might be due to an interaction with MidiQOL's troubleshooting function.

**Comment by thatlonelybugbear** [comment]
OK I think I can reproduce with Vision 5e, socketlib, libwrapper and Find the Culprit.

Needs a player connected and that error will be triggered on the player's client when you open the Configure Settings on the player's client.
Testing by connecting via Microsoft Edge for GM account and incognito Microsoft Edge for a player.

![image](https://github.com/dev7355608/vision-5e/assets/7237090/7d086f48-53cc-4c7c-9949-403b5ebb7ee6)

**Comment by dev7355608** [comment]
Ah, of course, makes sense: non-GMs can't configure the default hearing range. I'll fix it later today. Thanks!

**Comment by dev7355608** [comment]
Fixed.

https://github.com/dev7355608/vision-5e/releases/tag/v1.9.2
