### ISSUE TITLE
Switching back to Light Perception from other Vision Types on Token HUD

### ISSUE THREAD

**Issue by ButtFace1212** [dev7355608/vision-5e#39]
An issue i'm having is changing from a non-standard vision back to Light Perception. For example, this token has no darkvision, no hearing, Light perception, and Tremorsense 30 feet. The Light Perception works fine, but when I switch to Tremorsense, there is no way to switch back to Light Perception on the Token HUD other than going into the token settings and switching it back to Light Perception.

![image](https://github.com/dev7355608/vision-5e/assets/55815285/8126dd15-d9fd-4890-b1df-3f1632252cb4)
![image](https://github.com/dev7355608/vision-5e/assets/55815285/17327b32-2397-41ef-85cf-3bc556c84e84)
![image](https://github.com/dev7355608/vision-5e/assets/55815285/3eff8994-662b-45a5-88ce-c61884971e5d)

**Comment by ButtFace1212** [comment]
I've tested it with the scene having Global Illumination on and off if that matters

**Comment by dev7355608** [comment]
Thanks for the report! You can toggle vision modes off in the HUD now to get back to Light Perception.

https://github.com/dev7355608/vision-5e/releases/tag/v1.10.1
