### ISSUE TITLE
Placed tokens causing teardown to error (v11.299/300)

### ISSUE THREAD

**Issue by MiniGrief** [dev7355608/vision-5e#4]
Tested with only this module running on Chrome and Firefox on both Foundry v11.299 and v11.300.

Having a token placed down causes teardown to fail which means the old scene textures are not properly unloaded. This is most visible if you are on a scene with a large background image then swap to a scene with a small background image.

Based on the error below, I'm guessing it has something to do with 'SpriteMesh' in patches.js but don't know enough about this module, Foundry or PixiJS to say for sure. Both Chrome and Firefox gave slightly different error messages so I included both in case.

Chrome Error:

TypeError: Encountered an error while tearing down the previous scene: Cannot read properties of null (reading 'off')
    at SpriteMesh.destroy (index.js:126:1)
    at SpriteMesh.destroy (foundry.js:30509:42)
    at foundry.js:34313:42
    at Array.forEach (<anonymous>)
    at TokenLayer._tearDown (foundry.js:34313:27)
    at TokenLayer._tearDown (foundry.js:34816:18)
    at TokenLayer._tearDown (foundry.js:41861:18)
    at TokenLayer.tearDown (foundry.js:34301:16)
    at InterfaceCanvasGroup.tearDown (foundry.js:29071:21)
    at async Canvas.tearDown (foundry.js:26250:7)
    
Firefox Error:

TypeError: Encountered an error while tearing down the previous scene: this._texture is null
    destroy index.js:126
    destroy foundry.js:30509
    _tearDown foundry.js:34313
    _tearDown foundry.js:34313
    _tearDown foundry.js:34816
    _tearDown foundry.js:41861
    tearDown foundry.js:34301
    tearDown foundry.js:29071
    tearDown foundry.js:26250
    draw foundry.js:26120
    view foundry.js:23323
    _onClickScene foundry.js:78439
    jQuery 2
        dispatch
        handle

**Comment by MiniGrief** [comment]
Managed to make a temporary fix for this, not sure if it's how you'd want it fixing though or if any other issues could pop up with doing it like this though.

Changing texture loading in the section about the SpriteMesh to this fixes it:
`texture = await loadTexture(CONFIG.Token.documentClass.DEFAULT_ICON);
mesh.texture = texture;
mesh._texture = texture;`

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 1.1.4.
