### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Slagmoth** [dev7355608/vision-5e#44]
I would like the option to turn off token effects based on the detection method.

Example: The _See Invisibility_ spell indicates simply that "you see invisible creatures and objects as if they were visible" and only ethereal creatures are indicated as having any special, noticeable effect. The same is true for _True Seeing_ "see things as they actually are." which we take as you don't know what they appear to be only what they actually are. 

We were also toying with the idea of trying to detect areas of bright light to automatically disable Darkvision because in our games we don't allow it to be used in areas of bright light.

**Comment by dev7355608** [comment]
The description of the See Invisibility is poorly worded. I think it's meant to be a more "natural" wording of the following:

*"You see creatures that have the Invisible condition as if they didn't have the Invisible condition."*

I don't think it's supposed to mean that you see the creature as if there wasn't the magic/effect at all that is giving the creature the Invisible condition. It just negates the Invisible condition, but not the magic/effect of it. How you see the invisible creature is up to interpretation, I guess, but I think it's reasonable to assume that the player would still know what is and what isn't invisible.

Just today I stumbled over the Truesight description of the One D&D playtest, which specifically uses *Invisible condition* and not the adjectives *invisible*/*visible*.
> The creature can see creatures that have the Invisible condition and objects that are obscured by magic.

I hope they'll update the description of See Invisible as well.

But if you prefer, you can disable the See Invisibility detection mode filter with this in a world script.

```js
// Disable the filter effect on tokens detected by See Invisibility
Hooks.once("setup", () => {
    CONFIG.Canvas.detectionModes.seeInvisibility.constructor.getDetectionFilter = () => {};
});
```

And the invisibility effect on the token can be disabled with this:
```js
// Disable the Invisibility shader effect on tokens
Hooks.on("refreshToken", (token, flags) => {
    if (token.mesh?.shader.constructor === TokenInvisibilitySamplerShader) {
        token.mesh?.setShaderClass(InverseOcclusionSamplerShader);
    }
});
```

---

> We were also toying with the idea of trying to detect areas of bright light to automatically disable Darkvision because in our games we don't allow it to be used in areas of bright light.

When you step into bright light, the darkvision range is set to 0, but when outside of bright light, it's fine? I'll very likely won't implement this, as I don't have much time for module development at the moment, and I try to keep this module as RAW as possible.

**Comment by LukasPrism** [comment]
@Slagmoth this might be of some help? Unsure of compatibility but it’s been updated recently https://foundryvtt.com/packages/darkness-dependent-vision

**Comment by Slagmoth** [comment]
> The description of the See Invisibility is poorly worded. I think it's meant to be a more "natural" wording of the following:
> 
> _"You see creatures that have the Invisible condition as if they didn't have the Invisible condition."_
> 
> I don't think it's supposed to mean that you see the creature as if there wasn't the magic/effect at all that is giving the creature the Invisible condition. It just negates the Invisible condition, but not the magic/effect of it. How you see the invisible creature is up to interpretation, I guess, but I think it's reasonable to assume that the player would still know what is and what isn't invisible.

Totally understand. However, the funny thing about Invisibility's issues are deeper than that... I think the wording is fine however if you look at Jeremy Crawford's words on this, even if you see an invisible creature it doesn't remove the condition therefore they still get all the advantages if being invisible while still being seen... tbh I don't think Invisible should be a condition at all, as it isn't universal like the rest of them, as in none of the others can be negated situationally by someone else having a spell on them. Also, JC has said many times that "spells do what they say and nothing more" and we pretty much hold to that, so whereas an observant player could obviously sense something is amiss and tell immediately, just telling them right off sort of robs the PCs of their agency imo... 

In any event thanks for the code references, I am a .Net Dev by trade and haven't done much with JS but it has been on my list of todos, and moving from FGU to FVTT will allow me to become more familiar with more fun.

If I do wire up the Darkvision thing and put a setting on it I would be happy to throw a PR up for you if you want to add it to the module... I just feel the way Darkvision can be used RAW, again, robs the PCs of immersion and mystery. If I wasn't able to implement something like this I would likely have had to gone with a script per PC, which would have been tedious.

Thanks

**Comment by Dumbhuman** [comment]
> However, the funny thing about Invisibility's issues are deeper than that... I think the wording is fine however if you look at Jeremy Crawford's words on this, even if you see an invisible creature it doesn't remove the condition therefore they still get all the advantages if being invisible while still being seen...

Unfortunately it took until just a few days ago for the team to officially admit that such an interpretation was incorrect (no matter how much Jeremy Crawford refused to admit it).  Here's a snippet from the latest Unearthed Arcana, [Player's Handbook Playtest 7](https://media.dndbeyond.com/compendium-images/ua/ph-playtest7/tsgOb3llF22AL0nU/UA2023-PH-Playtest7.pdf?icid_source=house-ads&icid_medium=crosspromo&icid_campaign=playtest7) (page 41):

![image](https://github.com/dev7355608/vision-5e/assets/63615591/ed2ad6ef-3f05-412f-a6d2-785220ac8517)

Of course even more unfortunately the team has never been strong on editorial consistency, so their new definition still leaves a bit of room to argue that the only benefit lost if an Invisible creature is seen would be the last one (page 51).

![image](https://github.com/dev7355608/vision-5e/assets/63615591/a6b5cd01-787b-49c6-9f3a-38fa193225b1)

For whatever it's worth, I personally agree with the interpretation that an effect like See Invisibility or True Sight still allows the user to know Invisibility is being used even though they can see the target.
