### ISSUE TITLE
The latest version of Vision 5e is not auto updating

### ISSUE THREAD

**Issue by YenBenGrey** [dev7355608/vision-5e#45]
It is not in the list of updates for modules on The Forge, so I went to set up and then tried to update but it is saying that the latest version is up to date which is one version behind.
I opened edit on the module in setup and it says verified to 11.307 for Foundry, even if I manually change that to 11.308 it still won't upgrade the module to the latest version. 

I have put something in Module Troubleshooting too in the Foundry discord.

**Comment by YenBenGrey** [comment]
I uninstalled and went to install again and that is saying the p
<img width="641" alt="Screenshot 2023-09-11 at 09 02 08" src="https://github.com/dev7355608/vision-5e/assets/98095856/40985b08-7903-4e57-8680-24b208bb620d">
revious version

**Comment by dev7355608** [comment]
Oops. Thanks. Fixed.

https://github.com/dev7355608/vision-5e/releases/tag/v1.10.3
