### ISSUE TITLE
How do I work with Detect Magic?

### ISSUE THREAD

**Issue by stalker168** [dev7355608/vision-5e#46]
I'd like to know how you can link using the Detect Magic spell and enabling or adding detection mode. I haven't found any attributes on this topic, and I don't know how to write macros.
Also, is it possible to use this mode to detect "magic tiles" as it used to be in the ASE module?

**Comment by stalker168** [comment]
Thank you. But is it possible to somehow reveal magic symbols when they fall into the detection area?
If I use a token with the status Hidden or Invisible, then when detected, the base template of the token is displayed, not the image I supplied.

**Comment by dev7355608** [comment]
Detect Magic is what I call an imprecise sense: you can sense that there is magic at this location, but you don't know what kind of creature it unless you also see the creature. That why it shows the default token icon in place of the actual image. Hearing is another example of an imprecise sense.

I assume you try to place a token what is really a tile, and that tile is something like a glyph that is supposed to glow with Detect Magic? I'm afraid that's not possible.
