### ISSUE TITLE
Request: rename (or add) Invocation naming requirement

### ISSUE THREAD

**Issue by dineshm72** [dev7355608/vision-5e#49]
Right now, Devil's sight looks for a feature with the name "Invocation: Devil's Sight".  Similar for Ghostly Gaze and Witch's Sight.

The issue is that DDB names these features somewhat differently, e.g. "Eldritch Invocation: Devil's Sight".  Here's a screenshot from DDB, which is not exactly apropos because it is not exactly clear how the two levels are combined.  But based on how DDBI imports it, I'm guessing the JSON for the feature names it including Eldritch.
<img width="446" alt="image" src="https://github.com/dev7355608/vision-5e/assets/2231877/6e9a7748-fb03-4572-bfbc-3b4faf6f6a94">

I've asked Mr Primate about changing how DDBI imports it, but he has said doing so would like break a bunch of other things.  So I'm here to ask if you can either change the string that it's looking for to match DDBI, or perhaps add a second string that matches the above, or do some regex magic.  This would help automate the proper vision for those of us using DDBI to import PCs from DDB.

Thanks!

**Comment by dineshm72** [comment]
Here is how the feature imports from DDBI:
<img width="200" alt="image" src="https://github.com/dev7355608/vision-5e/assets/2231877/5afc67c8-6576-4b7f-96ee-bc15d86da47f">

**Comment by dev7355608** [comment]
I didn't know that. I can add to theses name to matching too. Not a problem.

Does DDB offer German and/or French translations? If so and the names are different, I'll need to add them too.

**Comment by MrPrimate** [comment]
> I didn't know that. I can add to theses name to matching too. Not a problem.
> 
> Does DDB offer German and/or French translations? If so and the names are different, I'll need to add them too.

It does not

**Comment by dineshm72** [comment]
There is also the Eldridge Adept feat, that offers a Devil's Sight choice.  Ideally we would catch that too.  I'm not positive what the DDB feature for that is called.

For edification, is there a reason you moved away from looking for an effect name and started looking directly for feats?

**Comment by dev7355608** [comment]
> For edification, is there a reason you moved away from looking for an effect name and started looking directly for feats?

Some feats don't have an active effect configured. I didn't want to make it a requirement to set that up first. And if there's a need for an active effect for devil's sight, that's possible with ATL.

**Comment by dev7355608** [comment]
But how would I know that an effect is supposed to give a certain detection mode if it could be named anything?

**Comment by dineshm72** [comment]
I meant that you would be the one to define it, very much like you're doing now, just with effects rather than feature names. Because the automation crowd can easily add effects, but we can't as easily modify feature names, given current tools, data sources, and workflows. For example, one of our automation guys was saying that his player has the Devil's Sight feat, so now he has to go in and rename it as though it were a warlock invocation in order to get Devil's Sight working right.

Instead, you might say "V5E will give Devil's Sight (PC version) to any token with an effect named "Devil's Sight", and Devil's Sight (monster version) to any token with an effect named "NPC Devil's Sight" (or whatever terminology you want to use).

Then the effect writers could write the features, feats, spells, etc. so that anything that should give the devil's sight effect adds an affect with that name, rather than having to rename features to match how you've built it.

But listen, I was just asking, to try to make things simpler for everyone.  No promises that my thoughts about are actually good technical ones.  If what we have now works well enough (with the changes proposed above), I'm fine with that too.

Thanks!

**Comment by dineshm72** [comment]
Maybe looking for either feature names or effect names would give the best of both worlds, at the cost of some additional complexity on your side.

**Comment by dev7355608** [comment]
@dineshm72: I misunderstood you. I thought you wanted that the effect name could be anything and it would work somehow.

I'll add alternative names for invocations. For example:
- Devil's Sight (will have a different effect on NPC actors)
- Invocation: Devil's Sight
- Invocations: Devil's Sight
- Eldritch Invocation: Devil's Sight
- Eldritch Invocations: Devil's Sight
- Eldritch Adept: Devil's Sight

I could also treat effects with names as if they are feats. But would it still be necessary if all of the above is picked up by the automation?

---

@Tallon159: Do you know the official French translation of Tasha's Eldritch Adept feat?

---

@mhilbrunner: Do you know the official German translation of Tasha's Eldritch Adept feat?

**Comment by dineshm72** [comment]
Sounds good to me.  Looks like you have the options covered for Devil's Sight.

**Comment by Tallon159** [comment]
@dev7355608 The official translation in tasha's book is "Adepte occulte"

**Comment by mhilbrunner** [comment]
@dev7355608: Just checked, it is "Schauerlicher Adept" (thanks for the ping!)

**Comment by dev7355608** [comment]
Thanks, @Tallon159 and @mhilbrunner!

---

Released https://github.com/dev7355608/vision-5e/releases/tag/v1.10.4.
