### ISSUE TITLE
Incompatible with DFred's Convenient Effects on "Add/Replace Mode"

### ISSUE THREAD

**Issue by txm3278** [dev7355608/vision-5e#5]
When using Replace mode with DFred's Convenient Effects to only have 5e conditions, it is impossible to add flying or inaudible to a token.

DFred's on add mode:
![image](https://github.com/dev7355608/vision-5e/assets/25332081/4e607331-1b6c-438e-b97f-38823355380d)

DFred's on replace mode:
![image](https://github.com/dev7355608/vision-5e/assets/25332081/6501c192-a72b-403c-ad6f-206ffd1fadd6)

**Comment by dev7355608** [comment]
You'll have to ask DFreds if it's possible to extend the list of conditions.

**Comment by txm3278** [comment]
Looks like an issue was already made over there https://github.com/DFreds/dfreds-convenient-effects/issues/253

**Comment by dev7355608** [comment]
Added compatibility in Vision 5e 1.3.0.
