### ISSUE TITLE
[feature request] Blood Sense

### ISSUE THREAD

**Issue by GameDevon** [dev7355608/vision-5e#50]
Can we have one that detects creatures that are under 50% hp? It would work roughly the same as detect magic

**Comment by GameDevon** [comment]
Yep. And only one character gets it when he casts a specific spell

**Comment by p4535992** [comment]
Similar request (always homebrew), but with more details commisionid and still open for anyone interested https://discord.com/channels/732325252788387980/1127554586622836838

**Comment by GameDevon** [comment]
> Similar request (always homebrew), but with more details and commisioned on the League Server for anyone interested https://discord.com/channels/732325252788387980/1127554586622836838

This link doesn't give access to the server on which it can be viewed on

**Comment by dev7355608** [comment]
Closing. I'll likely won't add another version of Blood Sense than was added.
