### ISSUE TITLE
(future request) Hearing

### ISSUE THREAD

**Issue by MaxorCore** [dev7355608/vision-5e#51]
First of all, this module is amazing, it brings a lot of depth and atmosphere and brings a solid foundation to gimmick your way into different visions.

I didn't find options to modify the "hearing" sense besides setting up a base value. If there are options are apologize.

Is it possible to set modifiers for the detection range of hearing via e.g. feats, traits, items, (convenient effects) or spells. For example I would like to reward a player for a successful perception check (most reasonable), create a custom spell that enhances hearing (maybe even trough walls) or other shenanigans. Also even though monster senses are a bit less relevant but I would like to imagine monster being capable to hear much farther than 30 feet.
On a smaller note since I think its harder to implement, but is it possible to reverse the hearing detection range with custom modifiers attached to for example Armor, so you can hear someone from further away because of the clunking armor?

**Comment by LukasPrism** [comment]
You could do a lot of what you’re after with Active Token Effects. There are AE keys for V5E in the readme, which will allow you to turn hearing on/off, extend the range etc with a high level of control. For the clunky armour you could maybe look into Active Auras and put an aura on the armor wearer that grants a hearing range extension to nearby creatures. Not a perfect solution but doable unless Eber implements something specific.

**Comment by dev7355608** [comment]
> I didn't find options to modify the "hearing" sense besides setting up a base value.

In case you didn't know: You can manually set the range of a detection mode on each token even if it's greyed out. Just add another detection mode of the same kind and set up a value. The greyed-out range (the one configured by the automation) will be overridden.

Other than that you should be able to configure hearing and other senses with Active Token Effects. I added an up to date attribute keys list to the readme of Vision 5e: https://github.com/dev7355608/vision-5e#active-effects.

Hearing is a difficult sense. Even if I made it more realistic, it would require a lot of inputs from the GM to configure how noisy everything is. The noise level could (quickly) change depending the state of the token (moving, speaking, ...). And walls: how thick are they and what are they made of? In combat it's reasonable to assume that everybody involved is very noisy unless they specifically make any effort to not make any noise, and so you'll be able to pin point the location accurately in close range without walls in between. The current hearing implementation is good enough for combat I think. But out of combat it isn't that useful and the GM pinging at the location of sound or narrating it is recommended.
