### ISSUE TITLE
[Feature Request] Detecting "Hollow Ones"

### ISSUE THREAD

**Issue by ZhornLegacy** [dev7355608/vision-5e#52]
Request for adding Hollow One (from EGtW p181-182) to sense features that can detect undead.
"..you register as undead to spells and other effects that detect the presence of the undead creature type..."

Add to Detect Evil and Good & Divine Sense

**Comment by dev7355608** [comment]
I assume you would entry this as a feat called "Supernatural Gift: Hollow One".

Summoning @mhilbrunner and @Tallon159 for official translations of "Supernatural Gift: Hollow One".

**Comment by mhilbrunner** [comment]
AFAIK, neither Theros (where Supernatural Gifts originate) nor EGtW were officially translated to German.

Fairly sure `Supernatural Gift` would be `Übernatürliche Gabe` in German. `Hollow One` is harder, as the literal translation is quite off and sounds bad. I'd probably go with `Hülle` (husk/shell), so if you want to use *something* at rather than nothing, `Übernatürliche Gabe: Hülle` would be my best effort. :)

**Comment by dev7355608** [comment]
I found these translations of the MTG card "Hollow One". Not D&D, but at least WotC.
- German: Leerwandler
- French: Celui-qui-est-creux

**Comment by mhilbrunner** [comment]
Ooh, nice one. Not sure they are the same, but thats still probably a better bet then. Guess `Übernatürliche Gabe: Leerwandler` it is then for German :)

**Comment by ZhornLegacy** [comment]
> I assume you would entry this as a feat called "Supernatural Gift: Hollow One".
Personally I'd have thought just go with "Hollow One" as "Supernatural Gift: [x]" in the title is a bit superfluous, just as we don't title other things as "Spell: Magic Missile" or "Feat: Heavy Armor Master" as those other descriptors or family groups are usually listed elsewhere.
![hollow_one](https://github.com/dev7355608/vision-5e/assets/106674701/b045881f-000a-41a7-abcc-055061e06ba2)

If the longer name is needed for mechanical reasons, then I'd just change to match what you end up using for the sake of being able to get the module to pick up on its presence for detection.

**Comment by Tallon159** [comment]
Is the Hollow One magic card the same as the feat in dnd? Because when you read the feat, you become an undead and the translation of the card doesn't capture that.

**Comment by dev7355608** [comment]
> Is the Hollow One magic card the same as the feat in dnd? Because when you read the feat, you become an undead and the translation of the card doesn't capture that.

Yeah, the magic card isn't about undeads, but still the translations should work for the dnd feat, I think, it's just a different kind of hollow.

---

https://github.com/dev7355608/vision-5e/releases/tag/v1.11.0
