### ISSUE TITLE
No functionality with Dfred Convenient Effects

### ISSUE THREAD

**Issue by Maradeurfv** [dev7355608/vision-5e#53]
Hi,

I noticed, that in Inaudible-Status-Effect of Dfreds Convnient Effects doesnt work with Vision5e. If a token has the Inaudible-Status-Effect from Dfred is still visible with hearing.

Would be rly nice, if that could be fixed.

Thx a lot for this fantatstic module!

**Comment by Ixrokis** [comment]
I had same issue, but as I checked it was in fact Dynamic Active Effects that caused Inaudible, Invisible and Burrowing effects to not work properly - it is working with Dfreds, but not DAE for me.

Also, I would ask - shouldn't Tremorsense not show creatures that flying? Or that are on elevation?

Anyway, I would also want to thank very much for this module!

**Comment by dev7355608** [comment]
I'm unable to reproduce it. Let me know if you can reproduce the issue in a new world, and, if so, which modules exactly are causing the issue.

**Comment by Ixrokis** [comment]
Hello,

I created new world, and Dynamic Effects using Active Effects module seems
to be the problem - when I'm deactivating it, token effects works again,
making them invisible etc.


niedz., 8 paź 2023 o 17:12 dev7355608 ***@***.***> napisał(a):

**Comment by dev7355608** [comment]
The only modules active modules are Vision 5e and Dynamic Effects using Active Effects, yes? Most recent version of dnd5e and both modules? I'll try to reproduce it later.

**Comment by Ixrokis** [comment]
I actualised Foundry and module, and now Dynamic Effects looks good and
working with Vision 5e, but now DFred Convinient Effects are causing to
invisibility not working - burrow, ethereal and so are good, but
invisibility have not effect
Pozdrawiam,
Bogusz Sikorski


pt., 13 paź 2023 o 17:10 dev7355608 ***@***.***> napisał(a):

**Comment by Ixrokis** [comment]
Ok, I think I located problem - when DFred Conviniet Effects will have
checked option to "replace" normal effects on token HUD, then the DFred
"invisible" effect is overriding original "invisibility". As burrowing,
inaudible or ethereal are new statuses, they are not overwritten, so the
are working and invisibility is not. When I'm not using replace option, it
seems to work.

sob., 14 paź 2023 o 09:24 Bogusz Sikorski ***@***.***>
napisał(a):

**Comment by dev7355608** [comment]
Sorry for losing track of this issue. I assume you have been able the issue by now. If not, let me know.
