### ISSUE TITLE
Tile layering and Share Media module interaction

### ISSUE THREAD

**Issue by niuserre** [dev7355608/vision-5e#54]
When the Vision-5e module is activated, Share Media's bounding tile becomes the highest layer and ignores tile z-index/ordering etc. I'm using Share Media to show images in a bounding tile on the canvas. I have a normal image tile layered over the top to create a soft edge for the image. 

Foundry v11 Stable 313 (DnD5e 2.3.1)
[Share Media](https://github.com/DarKDinDoN/share-media) 0.0.47

without Vision 5e:
![image](https://github.com/dev7355608/vision-5e/assets/1446741/7b30feb8-646a-48c1-8a4b-3e9615b7b827)

with Vision 5e enabled:
![image](https://github.com/dev7355608/vision-5e/assets/1446741/a92d3038-7270-4774-9156-4676905c2ec4)

I'd love to fix this so I can use both thanks! :)

**Comment by dev7355608** [comment]
Not sure what the issue was here or if it even is still an issue. I'll close it because Vision 5e received a major rewrite in V12, which could potentially solved any compatibility issues. If it is still an issue in V12, let me know.
