### ISSUE TITLE
feasibility question: hearing as direction instead of point

### ISSUE THREAD

**Issue by rapus95** [dev7355608/vision-5e#55]
How feasible would it be to implement hearing as a directed sense instead of a 2d pinpointing sense? Being able to pinpoint in a fog cloud doesn't feel that logical. Having a directional indicator on the other hand would feel awesome. Otherwise, it's just a free echolocation blindsight feature, which feels somewhat unbalanced. I know I could just set hearing range to 0, to drop it, but having a directional sense would be soo cool :D

**Comment by Dddsasul** [comment]
+1 on that, it basically reduces invisibility to nothing (yeah I know it's disadvantage on to hits but it just doesn't feel right when you have thing pinpointed on the map), it would be cool if it was direction based or have some global settings to disable it (and other modes). It does not fit the way I run my sessions.

**Comment by rapus95** [comment]
@Dddsasul you can effectively disable it by setting global hearing range to 0 in the settings.

**Comment by dev7355608** [comment]
Closing this. It's very unlikely that'll every take the time to implement this.
