### ISSUE TITLE
 [feature request] dichromate vision (minotaur)

### ISSUE THREAD

**Issue by GabrielLefevre** [dev7355608/vision-5e#56]
Is it possible to integrate a dichromate vision (configurable or not?). In my case it is for a minotaur player who only sees the world in shades of gray and red.

**Comment by dev7355608** [comment]
The Vision Color would ideally create this effect, but it can be a bit strong and increase the perceived brightness. Maybe it will get improved in the future. There's an core issue tracked for it.
