### ISSUE TITLE
Blindsight vs Hidden Creatures

### ISSUE THREAD

**Issue by NativeGuilt** [dev7355608/vision-5e#57]
I cannot seem to make a player token with Blindsight unable to perceive a creature that is hidden from them. Any advice on how to proceed?
I will note that this ability is coming from the Blind Fighting style, not the 14th level rogue ability, so creatures _can_ still be hidden from the player.

**Comment by dev7355608** [comment]
Hidden as in "Toggle Visibility State" from the token HUD? Or hidden in another sense? I assume the latter: I think you have situation where the player can still hear the creature. Search the [readme](https://github.com/dev7355608/vision-5e#readme) for *Hearing*: by default all tokens have 30 ft of hearing, and all tokens emit some level of sound that is audible unless they have the *Inaudible* status effect. If you don't like the hearing sense, you can set the *Default Hearing Range* to 0 in the settings.

**Comment by NativeGuilt** [comment]
Hidden as in the "Toggle Visibility State". I did notice the hearing thing and corrected it, but the blind token is still seeing hidden creatures.

**Comment by NativeGuilt** [comment]
Apologies, I assumed that the GM view becomes the player view when I select that token, but it would seem it isn't. Sorry for taking your time, I really love the module so far!
