### ISSUE TITLE
automagically swap the vision mode to the "best" sense available

### ISSUE THREAD

**Issue by rapus95** [dev7355608/vision-5e#59]
Right now, if you have darkvision and vision mode is darkvision, everything works fine. same for having darkvision and vision mode basic vision. (the latter one might not make sense though, since darkvision has different rendering than basic vision)
But if you have no darkvision but only one of truesight, devils sight and blindsight (and probably others I didn't check for) and the vision mode is set to the wrong one, you see the creatures but aside of that it's entirely dark. Vision mode needs to be set to the correct sense to work.
examples for blindsight:
![image](https://github.com/dev7355608/vision-5e/assets/5960902/c36a25b5-d01d-4f33-91ca-2502cdd22d90)
![image](https://github.com/dev7355608/vision-5e/assets/5960902/1617e83f-a0eb-446f-9cc7-1921b32ea64c)
![image](https://github.com/dev7355608/vision-5e/assets/5960902/a0794d5f-f9cc-4cd8-8c21-20c103e4c169)

ideally we could overlay all senses, but if that's not possible, easiest would be to have an order of "goodness" for the senses. Like if there's truesight for 20 feet, use that first. If there's blindsight for 40 feet, use that for 20-40 feet, if there's darkvision above that, use that outside of the 40 feet. And if there's no way to combine mutliple senses at once, use the best sense available for the range where your cursor is and just overlay the tokens onto that.

On top of that, what's the use of Vision mode Echolocation? There's no detection mode I could set for that.

and as a last one, actually rendering walls perceivable by the given senses, like echolocation, blindsight and so on would be very nice.

**Comment by dev7355608** [comment]
In 2.0.0+ the vision mode is set automatically initialized to the one with the largest range with the following priority:
Truesight over Blindsight over Devil's Sight over Darkvision.

**Comment by rapus95** [comment]
> In 2.0.0+ the vision mode is set automatically initialized to the one with the largest range with the following priority: Truesight over Blindsight over Devil's Sight over Darkvision.

So 60ft Truesight won't affect vision if I also have 120ft Darkvision? Sounds suboptimal. I'd love a hotkey that, when pressed, automatically swaps to the best sense for the range the cursor is at.

**Comment by dev7355608** [comment]
If you select Darkvision as the vision mode, Truesight still affects visibility even if not the selected vision mode. The detection modes detect things (tokens, door controls, notes) independently of the selected vision mode. You can switch between the vision modes via the HUD. The vision mode controls the FOV of the token and the visuals effects.
