### ISSUE TITLE
Easy way to switch back to "Basic Sight"

### ISSUE THREAD

**Issue by Falerion-git** [dev7355608/vision-5e#6]
Hi,

I have a charakter token, that has basic sight, dark vision and tremor sense.
![image](https://github.com/dev7355608/vision-5e/assets/75955095/b4711e6d-2625-458d-8815-622296c0bfb5)

After switching to dark vision, there seems to be no easy way to switch back to basic sight. So the player would stay in the gray color vision. If I switch it back to basic sight through the token configuration it switches back to normal sight.
![image](https://github.com/dev7355608/vision-5e/assets/75955095/e4b60c91-897b-43f3-8448-0c32a32ebcae)

Would be great if in the token HUD menu would also be the basic sight as option. Thank!

**Comment by dev7355608** [comment]
I assume you mean "Basic Vision" (the vision mode), not "Basic Sight" (the detection mode).

Why does this character use Basic Vision? What 5e sense or trait does this character have that allows them to see color? I don't want to add Basic Vision to the list, because it isn't a 5e sense: the list is supposed to show the list of available senses, not a list of vision modes.

**Comment by Falerion-git** [comment]
Hi,
thanks for your quick answer!
I guess my distinction between the vision mode and the detection mode was not that clear to me.

Let's assume you have a D&D 5e human, who has a magic item that gives him "Darkvision". That human now comes into an anti-magic field and loses his ability of "Darkvision". How would such an situation be handled?  I would have assumed that in such case I would need to switch back his vision mode to "Baisc Vision"?

**Comment by dev7355608** [comment]
Assuming the magic item applies the darkvision via an active effect, then you'd simply need to suspend the effect while inside the anti-magic field. When you select Darkvision and the token doesn't have darkvision, then it actually sets the vision mode to Basic Vision. This might not happen automatically yet when the token loses darkvision. I'll need to look into that.

**Comment by dev7355608** [comment]
> This might not happen automatically yet when the token loses darkvision.

This should happen automatically in 1.2.0 now.

**Comment by LukasPrism** [comment]
The easy way would be to have an AE providing the darkvision and just suspend it. This could even be a toggle macro from the hotbar. Or have it on an item and unequip it. I don’t think we’d want every player to be able to turn their racial darkvision on/off

**Comment by dev7355608** [comment]
@R0TEAM Why exactly do you want to use the Basic Vision mode instead of Darkvision for darkvision? Does the player character have a special kind of darkvision? Colored darkvision?

**Comment by R0TEAM** [comment]
> @R0TEAM Why exactly do you want to use the Basic Vision mode instead of Darkvision for darkvision? Does the player character have a special kind of darkvision? Colored darkvision?

yes - the players have an adjusted darkvision - and in special cases, the basic vision is better suited - and imho switch "back" to basic vision is always an downgrade and should be no problem from balance point ...

**Comment by dev7355608** [comment]
What kind of adjustments? You want darkvision of a particular character to have a different look, correct? Something like Fire Genasi darkvision?

In the list appear only 5e senses. It isn't supposed to be list of vision modes. Basic Vision can be an upgrade, because it allows you to see colors by default.

**Comment by dev7355608** [comment]
I'm closing this issue. Adding Basic Vision to the list is not something I'm going to do, because it isn't a 5e sense. If the request is about stylistic variations of darkvision like Fire Genasi darkvision, I'm open to considering that: please open a new issue for that.
