### ISSUE TITLE
Darkvision is broken after update

### ISSUE THREAD

**Issue by Maradeurfv** [dev7355608/vision-5e#60]
Darkvision no longer works since the last update with dfreds convenient effcest.

**Comment by dev7355608** [comment]
Broken in what way? I don't think I touched Darkvision in the last update. It's working for me (Vision 5e 1.1.0, DFreds 6.0.0, dnd5e 2.3.1/2.4.0).

**Comment by Maradeurfv** [comment]
Tested it again. With Vision5e I have no Darkvision. See links attached.
![withvision5e](https://github.com/dev7355608/vision-5e/assets/146621810/a35dd8a3-5af2-40e4-8d19-0afedd5ea0a3)
![withoutvision5e](https://github.com/dev7355608/vision-5e/assets/146621810/c994374f-3375-4ee6-ad61-07a730e6fbd8)

**Comment by rapus95** [comment]
@Maradeurfv did you check whether the token has darkvision as vision mode? I'd assume this to be the same mechanic I am talking about in #59

**Comment by Maradeurfv** [comment]
tested it, no change at all.
