### ISSUE TITLE
[Feature Request] Add common rarity magical items to the detect magic detection mode

### ISSUE THREAD

**Issue by etiquettestartshere** [dev7355608/vision-5e#64]
The [readme](https://github.com/dev7355608/vision-5e/blob/main/README.md) (emphasis mine) says:

> Note: Magic items are considered magical if the rarity is uncommon or higher. Mundane items should not have a rarity. Unfortunately, all mundane items in the system's item compendium are incorrectly given the common rarity, which means that all items that originated from this compendium pack would be detected as magical. ***Until this is fixed***, common items are not considered magical to avoid a large number false positives.

This does seem to have been fixed somewhere along the line (currently dnd5e 2.4.1), so common items can be added to the detect magic detection mode to conform better to the rules.

**Comment by dev7355608** [comment]
I intend to keep ignoring common rarity until the system adds the "Is Magical" property to items. If I let common items be detected as magical now, items that were imported from the 5e compendium before the rarities had been corrected would suddenly be magical. There are also adventure modules out there that incorrectly assign mundane items the common rarity like the 5e system did and still do, which is also a problem. When the 5e system adds the "Is Magical" property, all mundane items with an incorrect common rarity will be migrated to have the "Is Magical" flag to true, and so we'd have the problem as if I'd remove the common filter now, but then at least it will be more intuitive for the user to fix this issue by simply unticking the "Is Magical" checkbox. The user might not be aware that strictly only magic items have a rarity by RAW, and so they'd have a hard time figuring out why a mundane item is erroneously detected as magical.

**Comment by etiquettestartshere** [comment]
fair enough

**Comment by dev7355608** [comment]
dnd5e 3.0 has added the "Magical" property, which replaces the rarity test in Vision 5e 1.13+.
