### ISSUE TITLE
A Magic Marker Item

### ISSUE THREAD

**Issue by RawrKrake** [dev7355608/vision-5e#69]
At the moment, the module detects magic/undead what so ever only on Actors. It would be fantastic to have a pre made token, which is invisible to the normal player but Light up with these modules. For Example someone turns on Detect Magic and Something starts to glow in the room which wasn'T seen before.

**Comment by LukasPrism** [comment]
I’d recommend using Item Piles module in conjunction with Vision 5E. Not only can you make item piles invisible like any other token, players can interact with them… essentially being able to pick up whatever the item is.

**Comment by RawrKrake** [comment]
Doesn't fix the problem I have at least the way I tried it. I still have to reveal the token by hand. What I would like to do is something that is only visible when Detect Magic is active.

**Comment by dev7355608** [comment]
This would require a new special status if no detection mode but Detect Magic should reveal the token. Is this homebrew or something that exists in official content?

**Comment by dev7355608** [comment]
Stale issue. Closing.
