### ISSUE TITLE
[Feature Request] Shared vision for certain actors

### ISSUE THREAD

**Issue by LukasPrism** [dev7355608/vision-5e#74]
I wonder if solving this problem would be possible with V5E?

In 5E there are certain spells/features which users are representing on the canvas with tokens. Some common examples would be Spiritual Weapon, Flaming Sphere, Dancing Lights, the Echo Knight's manifested echo.

This issue is with these kinds of player-controlled tokens and V5E is you don't want them to have vision or the player will be able to use them to see around corners etc while the token is selected. However if you don't give them some sight the player is effectively blind when moving these tokens. Ideally when these kinds of tokens are selected and during movement the player should still be able to see using their assigned character's vision. Perhaps there could be some kind of flag we put on these tokens to enable this?

Many thanks.

**Comment by dev7355608** [comment]
I made tokens without vision visible to their non-GM owners always in v1.14.0. Not quite sure if there isn't a downside to this behavior, but I'll guess we'll find out when someone complains.

**Comment by LukasPrism** [comment]
Thanks! It sounds like a different problem than the issue I was trying to describe but I’ll give it a try.

**Comment by LukasPrism** [comment]
OK I've done some experimenting and it seems if the summon token has its vision off, the player can only see what their main token can see while using the summon. This is great, thanks.

**Comment by dev7355608** [comment]
I realized that there isn't really a good reason that owned token with vision enabled shouldn't be visible like that too. Made the change in v1.14.1.

**Comment by dev7355608** [comment]
@LukasPrism FYI: Removed this feature in 1.14.2 and released it as a small, separate module: https://foundryvtt.com/packages/reveal-observable-tokens
