### ISSUE TITLE
Assumption about Ethereal Undead

### ISSUE THREAD

**Issue by Dumbhuman** [dev7355608/vision-5e#75]
I noticed this line in the latest update notes:

> Ethereal undead NPCs (ghosts) are now visible on the material plane. I made the assumption that there are no undead creatures that can shift into the ethereal plane without being visible from the material plane.

As one example, a Lich could cast Plane Shift or Etherealness (from a swapped spell in its stat block or a Spell Scroll) to enter the Border Ethereal and wouldn't be visible from the Prime Material Plane, because there's no specific rule that says otherwise.  Similarly, any undead able to use a spell or magic item to cast Blink, Plane Shift, Etherealness, etc wouldn't be visible from the Prime Material Plane.

The Ghost's Etherealness feature contains a very specific exception to the general rule that creatures on the Ethereal plane are normally invisible to creatures on the Prime Material Plane.  It isn't related to the Ghost being an undead, any more than the Night Hag's exception in its Etherealness feature (requiring a heartstone) is related to it being a fiend.  Consider that the Incubus/Succubus is also a fiend, but has no such exceptions in its Etherealness feature.

**Comment by dev7355608** [comment]
I improved the "ghost" detection in 1.14.2: anything undead with the traits "Incorporeal Movement" and "Etherealness" is assumed to be visible on the material plane while ethereal.

**Comment by Dumbhuman** [comment]
> I improved the "ghost" detection in 1.14.2: anything undead with the traits "Incorporeal Movement" and "Etherealness" is assumed to be visible on the material plane while ethereal.

That should work, assuming you mean "trait" in the general sense, rather than the specific stat block semantics where Incorporeal Movement is a "special trait" (labeled "feature" in Foundry) and Etherealness is an "action".

It might be a bit more future-proof to check for the phrase "is visible on the Material Plane while it is in the Border Ethereal" just in case Wizards of the Coast ever releases a non-undead creature with that version of Etherealness, but it's probably pretty low odds of that happening.
