### ISSUE TITLE
[BUG] Summoning Conflict

### ISSUE THREAD

**Issue by Larkinabout** [dev7355608/vision-5e#76]
Foundry 11.315
dnd5e 3.1.1
Vision 5e 1.14.1

It looks like there is a conflict with the summoning functionality.

1. Activate a feature with the Summon action type.
2. Make sure 'Place Summons' is ticked.
3. Click 'Use Ability'
4. See error and the summon is not placeable and canvas gets stuck until reload.

Clicking 'Summon' from the chat card does not cause the same error. Disabling Vision 5e does not result in an error using the steps listed.

![image](https://github.com/dev7355608/vision-5e/assets/105953297/36b16927-ba5b-4a80-8df4-71da5d8f083c)

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 1.14.2.
