### ISSUE TITLE
Light sources cancel out Detection Modes when used with Limits

### ISSUE THREAD

**Issue by ctbritt** [dev7355608/vision-5e#78]
When using a template that has a number of vision mode limitations on it, if there is a light source on any tokens (global or ambient light source) they will not respond to the various Detection modes. 

Easier to show than describe.
<img width="1092" alt="Screen Shot 1" src="https://github.com/dev7355608/vision-5e/assets/4516034/7f8a8ba7-4bd1-4295-a7bd-7d957f8dfd0c">
Here Devil's Sight is functioning correctly.
<img width="820" alt="Screen Shot 2" src="https://github.com/dev7355608/vision-5e/assets/4516034/c0750bfb-056c-4d2e-b398-c6391fe46d52">
Here, with a light source overlapping the tokens, Devil's sight (and other detection modes that allow revealing tokens) doesn't work.
<img width="756" alt="Screen Shot 3" src="https://github.com/dev7355608/vision-5e/assets/4516034/2710caf9-67c8-40b9-b6ea-e98db1168524">
Here, lights removed, the tokens in the "Darkness template" can't see, but can hear. Working as expected. No lights on scene. Not even global illumination
<img width="771" alt="Screen Shot 4" src="https://github.com/dev7355608/vision-5e/assets/4516034/01271f54-ffb8-451a-8fd5-4e5de3ff50b3">
As show, global illumination checked, but darkness set to 1. Devil's sight token isn't being triggered. 
<img width="691" alt="Screen Shot 5" src="https://github.com/dev7355608/vision-5e/assets/4516034/814a0aeb-53f5-412e-a9be-257e2f8fa5a2">
Worse, the tokens in the darkness template, should be blind, but aren't. They can see the other tokens, even in when Darkness set to 1 and global illumination turned on. 
![CleanShot 2024-04-09 at 17 45 23](https://github.com/dev7355608/vision-5e/assets/4516034/e9462833-f2d5-42ba-a2b7-577f8dfa443a)

Foundry 11.315
Dnd5e 3.1.1 and 3.1.2
Vision 1.14.2

only modules enabled: vision 5e, limits, libwrapper, socketlib.

**Comment by dev7355608** [comment]
Thanks for the report! Fixed in 1.14.3.
