### ISSUE TITLE
Compatibility: Stealthy.engine.isHidden call seems unnecessary

### ISSUE THREAD

**Issue by Eligarf** [dev7355608/vision-5e#79]
As of Stealthy 3.14.2, I don't believe you need the code in ./scripts/compatibility.mjs:58-83. I tried deleting these lines in my local copy of vision-5e, everything seemed to continue to work as expected. After restoring those lines, I then changed Stealthy's isHidden function to always return false (I don't use the isHidden internally anymore), and again, everything seemed to run as expected. Please let me know if I'm missing something here.

**Comment by dev7355608** [comment]
The combability code shouldn't execute if >=3.14.x: https://github.com/dev7355608/vision-5e/blob/193b73c1922240f02db9516639840985738fffa7/scripts/compatibility.mjs#L48-L55
Does it anyway?

I kept the code in there for users that use an earlier version of Steathly for some reason.

**Comment by Eligarf** [comment]
I missed line 53. Somehow. I guess it's good I'm not a professional coder anymore, lol.... It is working as you intend.

As an aside, is there a way that the devilsSight detection mode can have a range? It behaves slightly differently from darkvision (5e rules-as-written) in that darkvision turns dim->bright and dark->dim, whereas devilsSight just turns dark->bright, and Stealthy cares about this distinction because it applies perception disadvantage against things in dim light. The Devil's Sight that the 5E SRD compendium ships with has a 120' darkvision range effect, which means no tokens give disadvantage to perception since darkvision takes dim->bright and devilsSight takes dark->bright. If I remove the 120' darkvision, then of course Devil's Sight works  great against tokens in dark, but the player can't see the canvas or doors, etc. Probably running up against a Foundry limit, but I thought I'd ask.
