### ISSUE TITLE
Lantern of Revealing

### ISSUE THREAD

**Issue by ctbritt** [dev7355608/vision-5e#8]
How do you add ranges to detection modes with the Active Effects? for instance, I've got a lantern of revealing. It applies an AE of "See Invisibility" but with no keys. The range gets set to infinity, when it should be 30 feet. How does one set that? 

![CleanShot 2023-06-19 at 09 06 36@2x](https://github.com/dev7355608/vision-5e/assets/4516034/f50984e0-cb2b-44e0-849f-db0e98f8be7e)

**Comment by ctbritt** [comment]
![CleanShot 2023-06-19 at 09 07 11@2x](https://github.com/dev7355608/vision-5e/assets/4516034/338bd68d-a549-478d-8666-e510099dd53c)

**Comment by dev7355608** [comment]
Lantern of Revealing doesn't give you See Invisibility with a 30 feet range. It reveals all invisible creatures within the area of effect. From the perspective from the one who holds it is effectively See Invisibility with a 30 feet range, but others would be able to see the invisible creatures too. I'm not sure if there's a nice way to implement this at the moment. I'd have to look into that.

**Comment by ctbritt** [comment]
Ah, that's a good point. Yeah, that sounds a bit tricky.

**Comment by LukasPrism** [comment]
> Is there a way to create a "Reveal Invisibility" function that's tied to a template, maybe? So that anything that goes in or out of the template gets the reveal invisibility active effect? I'm just spitballing.

This could be done easily enough with Template Macros and a small macro that checks for the invisible condition and deletes it

**Comment by ctbritt** [comment]
Yeah but how would you add the invisibility when they left the aura? And what about tokens that never had invisibility... would they become invisible when they also left the aura range?

**Comment by ctbritt** [comment]
i think giving everyone the ability to see invisible while they're in the template area might be the way to go rather than deleting or adding invisible status.

**Comment by LukasPrism** [comment]
Yeah sorry I didn’t read up on the lantern, thought if they were revealed they’d stay that way until the GM reinstates it. So it would be a bit more complex, you’d need to add a flag or AE for “suppressed invisibility” and do a check for that on template exit, reapply invisibility.

Eber, sorry for spamming these threads. Chris, always happy to chat about this stuff on Tim’s server :) Someone may benefit from reading it here I guess.

**Comment by dev7355608** [comment]
Thanks for the Template Macros suggestion, @LukasPrism. Maybe there needs to be a status to suppress invisibility. Then the AE applied by the Lantern of Revealing template could just set this status and wouldn't need to modify other AEs on the actor. Another application of this status would be Faerie Fire.

**Comment by txm3278** [comment]
[Chris's Premades](https://foundryvtt.com/packages/chris-premades) made a macro for Lantern of Revealing that works really well

**Comment by chrisk123999** [comment]
Convenient Effects is smart enough to disable and reenable the Invisibility condition when the actor gains and loses immunity to Invisibility.

**Comment by dev7355608** [comment]
It doesn't look like I need to make any changes given there are already working solutions out there. Closing.
