### ISSUE TITLE
Token Light Perception set to infinity provides no vision of tokens

### ISSUE THREAD

**Issue by donsuave** [dev7355608/vision-5e#82]
Hello, Since updating I've noticed tokens without dark vision or another vision having their light perception value set to infinity allows them to perceive the scene, but no other tokens within it. Setting the light perception value to another value i.e. 100, allows this character to see tokens. It seems that light perception being set to infinity is not registering the player token to be able to see other tokens.

**Comment by dev7355608** [comment]
Updated to V12, dnd5e 3.2.0, and Vision 5e 2.1.0? I'm unable to reproduce this. Make sure Vision 5e is the only module enabled when you test this to rule out a compatibility problem with another module.

**Comment by donsuave** [comment]
Thanks for checking, I did some testing on my end and it seems to be triggered with the levels module enabled.
