### ISSUE TITLE
Vision 5e not showing any effects after upgrade to Foundry v12

### ISSUE THREAD

**Issue by deadpyxel** [dev7355608/vision-5e#85]
First of all, thanks for the excellent work on this. I have a weird behaviour that I am not really sure how to report, so I'll try to provide some details. It seems there's a conflict between this module and Levels (at least this is what `libwrapper` says).

I intend to do a similar report on Levels to see if there's any way we can find out what is going wrong.

## Description

When initializing the world with both `Vision 5e` and 

## Expected Behavior

There should be no errors or warning once the world loads up

## Actual Behavior

An error message (se screenshot below) about Limits and a warning notification about a conflict between Levels and Vision 5e is shown

## Possible Fix

I am trying to figure out if this is a Levels issue, a Limits issue or a Vision 5e issue, these are the only warning/error messages on console after world is loaded.

## Steps to Reproduce

1. Have Limits, Levels, Vision 5e and any dependencies installed
2. Create a new DndD 5e world on Foundry VTT v12
3. Load into that world and enable the modules
4. On reload, notice the error message and that the vision modes are now shown

## Context

I have recently been tackling the upgrade of my personal instance to Foundry v12 and this module seemed to have a warning triggered by `libwrapper`. I am not sure if there's an internal dependency in some special implementation from limits that is causing this issue, but I am working on a way to test some separate cases to pin down where the issue is.

Here is a screenshot of initialization:
![image](https://github.com/dev7355608/vision-5e/assets/8644691/bf618f3e-4c0b-433d-96ed-0ec759608475)

And here is the special detection modes not working, the actor on the left has detect magic of 30 feet while the one on the right has several magical items, no effects are showing and none of the detection modes seem to be rendering.
![image](https://github.com/dev7355608/vision-5e/assets/8644691/ae6ae3be-fee3-429c-be53-cf3a698e12ce)

![image](https://github.com/dev7355608/vision-5e/assets/8644691/ad7903b3-d701-4297-a6e0-2e7cc79b3765)

Similar has been shown with the detect evil and good, the actor on the right is evil, and should be shown to the actor on the left. No "Eye" icon is appearing.

![image](https://github.com/dev7355608/vision-5e/assets/8644691/d1d555fd-d63d-4ed7-91ed-025aebb20215)

## Environment

* Version used: 2.2.0
* Foundry Version: 12.325
* DnD5e System Version: 3.2.0
* The "Levels" addon is on version 5.1.2 (https://github.com/theripper93/Levels)

**Comment by dev7355608** [comment]
Limits hasn't been updated for V12 yet. So disable this one first. If the warning persists, let me know what the full warning message says in the console (F12 -> Console tab) (and potentially other error messages).

**Comment by deadpyxel** [comment]
Disabling Limits did not change much, the warning itself is like this:
![image](https://github.com/dev7355608/vision-5e/assets/8644691/5c4a4f8d-cfbe-4a51-8bb6-a6fc4fb088f6)

I believe the second warning message is unrelated as there are other instances of it before the libwrapper one.

The only other error message I have on the console is from another module (Combat Enhancements), but that happens way before this warning appears.

**Comment by dev7355608** [comment]
I fixed the warning in 2.3.0. If it still doesn't detect, double-check that the items have in fact the Magical property: note that in older dnd5e version this property did not exist and Vision 5e had to infer whether it's a magical item or not based on the Rarity of the item. I forgot which version of dnd5e introduces the Magical property, but as a consequence all existing items didn't have the Magical property, and so Vision 5e no longer detected them having switched from a Rarity-based check to the Magical property check.

**Comment by deadpyxel** [comment]
Property is present, and while the warning does not show anymore, the eye icon on token hud and such effects still not present.

Here is the item details 
![image](https://github.com/dev7355608/vision-5e/assets/8644691/230d00df-cfa9-45b6-b6c3-2b21bd2d6915)

In the sheet, the. "magical" icon is shown for said item (a Moon Touched battleaxe)

Console log has no module messages beside the ones as follows:
```
Foundry VTT | Loaded localization file modules/vision-5e/lang/en.json
```

Disabling Levels did not seem to fix the issue.

**Comment by dev7355608** [comment]
Could you try disabling all modules except Vision 5e and check if the issue persists (if you haven't done so already)? I tested earlier and everything was working as expected. Surely some other modules must be conflicting somehow, but odd that you don't see any error messages in the console if that is the case.

**Comment by deadpyxel** [comment]
Ok, So I did some testing on a completely new world, running with the same versions as a minimum setup

Here is the list of enabled modules:
![image](https://github.com/dev7355608/vision-5e/assets/8644691/09cb0d90-2bb0-410e-8c4c-02e3c7c4acf5)
You can ignore the TidyUI modules, the tabulanil (that's mine, and does not touch any of the token vision code)

The result is this:
![image](https://github.com/dev7355608/vision-5e/assets/8644691/b7a719c9-de1f-4fd8-92ac-29fd0ff77697)
![image](https://github.com/dev7355608/vision-5e/assets/8644691/b0322802-3bd0-443d-b99b-888f677ef6d8)


Now, enabling Levels:
![image](https://github.com/dev7355608/vision-5e/assets/8644691/2a17b05d-65ad-4f77-a439-bb465b828584)

It works!
![image](https://github.com/dev7355608/vision-5e/assets/8644691/9c034267-fac2-411c-bcac-5cc2a732c4c1)

But that said, no "Eye" icon is seem in both cases
![image](https://github.com/dev7355608/vision-5e/assets/8644691/2fbc315f-14bf-4a77-84c6-829d5621b7dd)


Now, I am slowly bringing up the other modules into this instance to find the faulty one, but I thought you should know about this behaviour.

**Comment by dev7355608** [comment]
>But that said, no "Eye" icon is seem in both cases

I realize that only now but now Eye icon is expected if the token has only one of Darkvision, Devil's Sight, Truesight, Blindsight, because in this case it wouldn't have have a choice. It's a bit different from Vision 5e 1.x.

**Comment by deadpyxel** [comment]
> > But that said, no "Eye" icon is seem in both cases
> 
> I realize that only now but now Eye icon is expected if the token has only one or none of Darkvision, Devil's Sight, Truesight, Blindsight, because in this case it wouldn't have have a choice. It's a bit different from Vision 5e 1.x.

So If I understood, if the token has no "normal vision" only one of the three, it will have the Eye icon showing, is that correct?

**Comment by deadpyxel** [comment]
Just for documentation purposes (and my sanity) the modules I have enabled on my world are this ones:
```
Active Modules:
----------
Alternative Exhaustion v1.0.2;
Anonymous v1.5.1;
Automated Animations v4.2.72;
Baileywiki Mass Edit v1.68.0;
Better Roofs v2.0.3;
Boss Bar v2.0.2;
Boss Loot FX Animated Assets Free v2.0.0;
Caeora's Maps, Tokens, and Assets v2.1.5;
Caeora's Patreon Maps, Tokens, and Assets v2.0.0;
Caeora's Token Hoard v2.0.2;
Combat Booster: Turn Marker, Recent Actions and more v4.0.0;
Combat Enhancements v1.2.3;
Cze and Peku's Sample Pack v;
D&D5e Animations v1.6.2;
D&D Item Compendium by Gwillewyn v1.0.1;
Dice So Nice! v4.6.10;
Dice Tray v2.1.11;
Drag Upload (Get Over Here!) v2.3.0;
Dynamic Soundscapes v2.0.0;
Epic Rolls 5e v4.0.1;
Ethck's 5e Downtime Tracking v0.7.6;
Filepicker + v4.0;
Forgotten Adventures Battlemaps v1.0.60;
FXMaster v4.0.2;
Gatherer v3.0.1;
GM Vision v1.1.3;
Health Estimate v32.0;
Hover Distance v4.0;
Ivan Duch's Music Packs v2.4;
JB2A - Jules and Ben's Animated Assets - Free Content v0.6.8;
JB2A - Patreon Complete Collection v0.6.7;
Let's Trade 5e v0.6.0;
Levels v5.1.2;
lib - Color Settings v3.0.3;
Library: Scene Packer v2.7.12;
Library: Wave Function Collapse v1.0.5;
libWrapper v1.12.13.1;
Loot Tavern Free Item Compendium v2.2.2;
Mastercrafted - Crafting Manager v3.0.0;
Media Optimizer v3.0.0;
Monk's Active Tile Triggers v12.01;
Monk's Combat Details v12.01;
Monk's Enhanced Journal v12.01;
Monk's Little Details v12.02;
Monk's Scene Navigation v12.01;
Moonlight Maps v1.1.1;
Multilevel Tokens v1.7.0;
Not Your Turn! v2.2.0;
Party Overview v2.18.0;
Pin Fixer v1.2.2;
Pings v1.4.1;
Polyglot v2.4.14;
Puzzle Locks v2.0.0;
Ready Set Roll for D&D5e v3.1.0;
Rest Recovery for 5E v1.12.0;
Revised Weapons & Equipment v11.0.0;
Sequencer v3.1.4;
Settings Extender v1.2.2;
Simple Quest v2.0.3;
Smart Target v2.0.0;
socketlib v1.0.13;
SoundFx Library v1.0.3;
Status Icon Counters v2.1.2;
Tabletop RPG Music v3.2.1;
tabulanil' sanity system for 5e v0.7.0;
Tagger v1.4.5;
TheRipper93's Module Hub v3.0.3;
Tidy UI - Game Settings v0.1.52;
Tile Scroll v3.0;
Token Action HUD Core v1.5.3;
Token Action HUD D&D 5e v1.5.7;
Token Flip v2.0;
Token Frames v1.6.3;
Tokenizer v4.3.8;
Token Magic FX v0.6.7;
Token Variant Art v4.64.3;
Torch v2.13.1;
Traps, Trammels, and Triggers v11.0.0;
Vision 5e v2.3.0;
Wall Height v6.0.6;
Warp Gate v1.closing;
Wild Magic Surge Companion Module for Animated Spell Tokens v1.3.0;
World Anvil Integration v1.4.5;
```

These are the active modules on the world I detected the problem. If there's any incompatibility you already know, please let me know, I think there's probably one or two in this list that are not being used and I should delete/disable. I'll keep on enabling then one by one trying to focus on the ones that change UI or similar stuff.

**Comment by dev7355608** [comment]
Nothing jumps out at me quickly scanning through these modules, and I'm not aware of any incompatibilities in V12.

**Comment by deadpyxel** [comment]
I have not been able to reproduce it on that test instance, but I am not trying on my "production" one. In both every time I change the vision mode (from darkvision to blindsight for example, using the eye icon), the console has some deprecation warning being shown like this:
![image](https://github.com/dev7355608/vision-5e/assets/8644691/fda00278-1208-4130-87bc-88663fd223ba)

I don't think this is related, but I have been trying different combination and something is probably very wrong with my instance, just not sure what yet. Is there any chance that some remaining file from the upgrade (foundry itself is a fresh install, what has been migrated is the foundrydata folder) may be affecting this?

**Comment by V0ren** [comment]
I have ran into a similar issue with the 'hearing' not rendering. I could not see any errors related to vision5e in the console, but after disabling other modules I managed to get it working. For me the culprit was "Health Estimate", and I can see @deadpyxel also has it in the list. I am not sure what Health Estimate is doing that might be causing this.

**Comment by dev7355608** [comment]
Thanks @V0ren, that was helpful. Fixed it: https://github.com/dev7355608/vision-5e/releases/tag/v2.3.1.

**Comment by deadpyxel** [comment]
This is interesting, I'll check it out soon. I could not reproduce in the
test instance, but I did not get to health estimates on my main instance.
Thanks for all the help and work
