### ISSUE TITLE
[Feature Request] Clarification on Perfect Vision Light Levels

### ISSUE THREAD

**Issue by Hawketotrot** [dev7355608/vision-5e#87]
Core allows only to boost dim to bright light in the entire scene. That's what the core Darkvision vision mode does. Vision 5e changes this so that you don't see every light as bright outside of your darkvision range, but that also mean you don't see it as bright within the range. Implementing it they way Perfect Vision would be very hacky and a lot of effort, so the decision was made early that Vision 5e won't try to make darkvision behave rules-accurate in this regard.

_Originally posted by @dev7355608 in https://github.com/dev7355608/vision-5e/issues/86#issuecomment-2186409241_
            
            
Except thats not what your module does and you know that, so to act like it does is kinda asinine. I don't want the grayscale vision in Darkness and your Dim light still is brighter than regular Dim. I don't want Dim to be upgraded at all. Not having any sort of customization to your vision module is not exactly user friendly and your module still doesn't allow for certain lighting effects to look good because your Darkvision Dim Light is still brighter than the Dim light experienced by tokens without Darkvision.

**Comment by Hawketotrot** [comment]
Just gonna close it since dev is too lazy to admit he is wrong or just doesn't understand the request.

**Comment by dev7355608** [comment]
I obviously have read you first issue wrong expecting another request for an accurate dim to bright boost like Perfect Vision did. Vision 5e uses a Vision Brightness of 0.1 instead of 0 to fake a dim to bright boost within range. If you want to change that and set it to 0, you may do so via a world script:
```js
Hooks.once("setup", () => {
    CONFIG.Canvas.visionModes.darkvision.updateSource({ vision: { defaults: { brightness: 0 } } });
});
```
