### ISSUE TITLE
[Bug] SpecialStatusEffects DAE Incompatibility

### ISSUE THREAD

**Issue by ScoflWorks** [dev7355608/vision-5e#88]
**Description**
Detection modes that rely on `specialStatusEffects` (such as Witch Sight) do not function when the module Dynamic Active Effects (DAE) is enabled.

**Steps to Reproduce**
1. Place any actor token on a scene with vision enabled
2. Grant the actor Witch Sight via the token configuration menu
3. Place an actor with the "Shapechanger" trait (such as a Werewolf) next to the first actor
4. Observe how with DAE disabled, the werewolf is detected, but with DAE enabled, the werewolf is not
5. Select the werewolf token, open the console, and enter `_token.actor.statuses`
6. Observe how with DAE enabled, the werewolf has no statuses

**Versions**
Foundry Version: 12.328
DND5e Version: 3.2.1
Vision 5e Version: 2.3.1

**Other Modules**
DAE 11.3.33
libWrapper 1.12.13.1
socketlib 1.0.13

**Likely Cause**
DAE's `applyDaeEffects()` function appears to clear all non-active effect statuses.

**Comment by dev7355608** [comment]
I don't think I can do anything about that. I don't know why `applyDaeEffects` wipes the `statuses`. It looks like DAE needs some changes.

**Comment by tposney** [comment]
This is definitely a dae bug, not perfect vision. I'll have a look at it.

**Comment by ScoflWorks** [comment]
This appears fixed as DAE 11.3.35. Thank you both for your time.
