### ISSUE TITLE
Vision/Detect Modes 5e causes increasing extreme movement lag based on the number of Tokens on a scene

### ISSUE THREAD

**Issue by Aeristoka** [dev7355608/vision-5e#9]
1. Create scene with many walls (example attached).
2. Start with a single PC Token (even with only Hearing sense from Vision/Detection 5e)
3. Move token (moves normally with v11 performance)
4. Start adding tokens throughout map
5. Observe movement performance slowly start lagging, then suddenly proceed to extreme movement lag
6. Disable Vision/Detection 5e, Movement is smooth once again (with all tokens on map).

This is about the breakpoint where things get really noticeably laggy:
![image](https://github.com/dev7355608/vision-5e/assets/7988297/fff3e0a3-085c-4bf1-b6bd-f6c2ada5d9ff)

(noticeable before, but "bearable")

[fvtt-Scene-sewers-1-(copy)-(copy)-Eei0JhqKFKhksBTX.zip](https://github.com/dev7355608/vision-5e/files/11801365/fvtt-Scene-sewers-1-.copy.-.copy.-Eei0JhqKFKhksBTX.zip)

**Comment by dev7355608** [comment]
That are probably the many ray casting test that are performed by the hearing mode. Those aren't particularly fast. I assume if you override the hearing range to 0, there's no lag, right?

**Comment by Aeristoka** [comment]
> That are probably the many ray casting test that are performed by the hearing mode. Those aren't particularly fast. I assume if you override the hearing range to 0, there's no lag, right?

How/where would one override the hearing range? I'll happily test that.

**Comment by dev7355608** [comment]
Unless the hearing range is very large, 1.4.0 should fix this issue. Now the range is tested first, and second the walls for line-of-sight (line-of-hearing). This improves the performance substantially, because the expensive part (the LOS check) is not performed for tokens out of hearing range. This change also improves other detection modes that perform a ray casting check to test LOS.

**Comment by Aeristoka** [comment]
> Unless the hearing range is very large, 1.4.0 should fix this issue. Now the range is tested first, and second the walls for line-of-sight (line-of-hearing). This improves the performance substantially, because the expensive part (the LOS check) is not performed for tokens out of hearing range. This change also improves other detection modes that perform a ray casting check to test LOS.

Tested 1.4.0 with the example scene I posted here, it is fixed indeed!

Thanks for all your hard work on all these Modules, and now FoundryVTT core. Makes me feel real good about the performance and stability of the lighting engine of FoundryVTT going forward.
