### ISSUE TITLE
[Bug/Feature Request] Hearing is "obscured" by less than total cover

### ISSUE THREAD

**Issue by mcabel** [dev7355608/vision-5e#90]
Bug: When a token is sufficiently obscured (some amount greater than 50% but ) less than 100% cover (for example 3/4 cover), an invisible enemy within valid hearing distance, can not be "heard" any more. 

To test, I set up a token enemy with 16 Passive perception, with hearing distance formula of 45 + 2.5 * (@skills.prc.passive - 10)  which nets 60ft.

I used the module gm vision ( https://foundryvtt.com/packages/gm-vision)  to see through the darkness for testing purposes, but the bug happens with only Vision 5e enabled.

I will attach a picture below showing the walls and a line that shows the distance and 3/4 cover between an attacker and an invisible target.

Feature Request/Enhancement:
Aside from being able to hear this invisible target, it would be amazing if it could be heard when **not invisible** in the same situation. A second image shows the (potentially audible) target totally obscured and with no sound waves; adding them in such case would be a helpful improvement.

When I remove the invisibility condition, the token cannot be seen or heard.

Specs: Foundry v12.3, DND 3.3.1

Note: If I had to guess, maybe vision and hearing is being calculated to the center of the token, which would fool the senses into thinking that the target has full cover, instead of using the corners like in dnd 5e dmg, but I'm just speculating...

![image](https://github.com/user-attachments/assets/c5006acf-ec77-41ad-86fd-43da4bda70f7)

![image](https://github.com/user-attachments/assets/3eb72d70-0ae9-4f7b-9f96-dbe88f2196d4)

**Comment by dev7355608** [comment]
9 points are tested arranged like this: 
![image](https://github.com/user-attachments/assets/e7c61488-dd57-4e60-a9f6-16124da84d59)
That's how Foundry does it. If their are all not in line of sight, the token isn't visible.

In this particular situation it might be a good choice to make the walls of the pillar not block sound.

There's the [Alternative Token Visibility](https://foundryvtt.com/packages/tokenvisibility) module that has options to change the way visibility is tested. But I'm not sure if this module is a 100% compatible with Vision 5e in V12.

There's also the [Token Lean: Peek Around Corners](https://foundryvtt.com/packages/token-lean) module that can be a solution for this kind of situation.
