### ISSUE TITLE
[BUG] New Darkness in v12 blocks hearing.

### ISSUE THREAD

**Issue by Ikabodo** [dev7355608/vision-5e#93]
Looks like the new fancy darkness "lights" in v12 block hearing.

**Comment by dev7355608** [comment]
It's working correctly for me. Perhaps incompatibility with another module?

**Comment by Ikabodo** [comment]
> It's working correctly for me. Perhaps incompatibility with another module?

Interesting! It looks like it was Levels! Not sure what end the issue is. Do you prefer me to put a report there?

**Comment by dev7355608** [comment]
> Do you prefer me to put a report there?

Yeah. Very likely something that needs to be fixed in Levels. I suspect Levels ignores the `includeDarkness` property and includes darkness edges always.
