### ISSUE TITLE
Bug: Devils Sight and True Sight not displaying actors within a Darkness Source

### ISSUE THREAD

**Issue by gambit07** [dev7355608/vision-5e#94]
Foundry's V12 darkness source option does not appear to be working with v5e's Devil Sight and True Sight option for actors outside of the darkness source. If the actor is within the darkness source with vision, they are able to see other actors, but the glow effect from V11 is no longer present highlighting actors they can see. Video attached for reference.

https://github.com/user-attachments/assets/361a8a85-53d2-47a1-a37d-43ac0228d09c

**Comment by dev7355608** [comment]
Do you use the Levels module? There's currently a compatibility issue would explain this.

**Comment by gambit07** [comment]
> Do you use the Levels module? There's currently a compatibility issue would explain this.

Ah interesting, yes that does seem to resolve them being visible,, thanks for the info. 

That being said, there is still no outline for the truesight/devils sight effect so it makes it very difficult for the actor outside to see a token within that darkness type area. On v11 there was a unique outline/aura for truesight and devils sight, so not sure if that's a bug or if the outline/aura was removed in v12
