### ISSUE TITLE
Heard Token Corresponding to Combatants in the Combat Tracker and Vice Versa

### ISSUE THREAD

**Issue by puddleimages** [dev7355608/vision-5e#96]
Players can still tell which token is which even when they only "see" the token via hearing it. By hovering over the heard token on the canvas or the corresponding combatant in the combat tracker, users can see the corresponding token or combatant highlighted. Is there a way to conditionally shut of this highlighting? Toggling a combatant's visibility on the combat tracker is almost a good solution, but some creatures may be heavily obscured to one token and not to another. Since each player token may hear and see different creatures it would be nice to implement something to help avoid the unintentional meta gaming that this facilitates.

**Comment by dev7355608** [comment]
Fixed in 2.3.3. https://github.com/dev7355608/vision-5e/releases/tag/v2.3.3
