### ISSUE TITLE
Magical darkness and Devil's Sight/Truesight

### ISSUE THREAD

**Issue by DesertEagle50** [dev7355608/vision-5e#98]
While all tokens are inside magical darkness both Devil's Sight and Truesight work as intended. But viewing from outside the darkness source you still can't see or hear the tokens inside the magical darkness. Is that a limitation of the system or a glitch on my end maybe?

**Comment by dev7355608** [comment]
It should work was expected from the outside. It could be compatibility issue with another module perhaps.

**Comment by DesertEagle50** [comment]
I'll try turning everything else off.

**Comment by gambit07** [comment]
> I'll try turning everything else off.

This is likely Levels, Levels is incompatible with Vision5e in regard to Magical Darkness sources

**Comment by dev7355608** [comment]
This compatibility issue needs to be fixed on Levels side. Here's the thread of ripper's discord regarding the incompatibility: https://discord.com/channels/844900867240361984/1270365132676927551
